package hackerrank;

public class Abbreviation {

    private static Integer COUNT = 0;

    private static Integer checkIfHasBeingCoveredAlreadyOrNull(String a, int indexOfFirstLowCaseOfMostRecentSequence, int currentAIndex) {

        System.out.println("recur, string:" + a + " start-ind:" + indexOfFirstLowCaseOfMostRecentSequence + " cur:" + currentAIndex);


        for (int inda = indexOfFirstLowCaseOfMostRecentSequence; inda < a.length(); inda++) {
            char underScopeLowCase = a.charAt(inda);
            char underScopeUpperCase = a.charAt(currentAIndex);
            if (Character.toUpperCase(underScopeLowCase) == underScopeUpperCase) {
                currentAIndex++;

            } else {
                System.out.println("end recur, cur:" + currentAIndex);
                return currentAIndex + 1;
            }
        }

        System.out.println("last end recur, cur:" + currentAIndex);
        return currentAIndex;
    }

    private static boolean checkUpperCharsAfterYes(String a, int currentIndex) {
        String debugLeftOverA = a.substring(currentIndex);
        System.out.println(debugLeftOverA);

        for (int j = debugLeftOverA.length() - 1; j >= 0; j--) {
            if (Character.isUpperCase(debugLeftOverA.charAt(j))) {
                char inscope = debugLeftOverA.charAt(j);
                char inscopeLeftOver = a.charAt(currentIndex - 1);
                if (inscope == Character.toUpperCase(inscopeLeftOver)) {
                    currentIndex--;
                } else {
                    return false;
                }

            } else {
                //ignore
            }
        }
        return true;

    }

    public static String abbreviation(String a, String b) {
        // Write your code here
        int match = 0;
        int i = 0;
        int indexOfFirstLowCaseOfMostRecentSequence = -1;
        boolean startOn = true;

        for (int inda = 0; inda < a.length(); inda++) {
            char fromA = a.charAt(inda);
            //b has finished
            if (i == b.length()) {
                //a has more uppercase

                boolean b1 = checkUpperCharsAfterYes(a, inda);
//                System.out.println("b1:"+b1);
                //all extra already included?

                if (checkUpperCharsAfterYes(a, inda)) {
                    return "YES";
                } else {
                    return "NO";
                }
//                if( Character.isUpperCase(fromA)) {
//                    return "NO";
//                } else if (match == b.length()) {
//                    //check if there are more UpperCases and are a match or a mismatch
//                    return "YES";
//                }
                //a has no more uppercase
            } else {
                if (inda == 61 || inda == 71 || inda == 142) {
                    System.out.println("Stop");
                }
                String debugLeftOverA = a.substring(inda);
                String debugLeftOverB = b.substring(i);
                System.out.println("-");
                System.out.println(debugLeftOverA);
                System.out.println(debugLeftOverB);

                //b has not finished
                char fromB = b.charAt(i);
                //is a match
                if (Character.toUpperCase(fromA) == fromB) {
                    match++;
//                    i++;
                    if (fromA != fromB && startOn) {
                        indexOfFirstLowCaseOfMostRecentSequence = inda;
                        startOn = false;
                    }


                    i++;
                } else if (Character.isUpperCase(fromA)) {
                    if (indexOfFirstLowCaseOfMostRecentSequence != -1) {
                        int newIndex = checkIfHasBeingCoveredAlreadyOrNull(a, indexOfFirstLowCaseOfMostRecentSequence, inda);
                        inda = newIndex - 1;//-1 due to auto increment in the next iteration
                        startOn = true;
                    } else {
                        return "NO";
                    }

                }
                //is no match
            }
        }

        return match == b.length() ? "YES" : "NO";

    }

    private static String solution(String a, String b) {
        boolean[][] isValid = new boolean[a.length() + 1][b.length() + 1];
        isValid[0][0] = true;
        COUNT++;

        for (int i = 1; i <= a.length(); i++) {
            COUNT++;

            if (Character.isUpperCase(a.charAt(i - 1))) {
                isValid[i][0] = false;

            } else isValid[i][0] = true;

        }
        // tabulation from start of string
        for (int i = 1; i <= a.length(); i++) {
            for (int j = 1; j <= b.length(); j++) {
                COUNT++;

                if (a.charAt(i - 1) == b.charAt(j - 1)) {
                    isValid[i][j] = isValid[i - 1][j - 1];
                } else if (Character.toUpperCase(a.charAt(i - 1)) == b.charAt(j - 1)) {
                    isValid[i][j] = isValid[i - 1][j - 1] || isValid[i - 1][j];
                } else if (Character.isUpperCase(a.charAt(i - 1))) {
                    isValid[i][j] = false;
                } else {
                    isValid[i][j] = isValid[i - 1][j];
                }
            }
        }
        return isValid[a.length()][b.length()] ? "YES" : "NO";
    }

    public static void main(String[] args) {
//        System.out.println("1 "+abbreviation("AbcDe", "ABDE").equals("YES"));
//        System.out.println("2 "+abbreviation("AbcDE", "AFDE").equals("NO"));
//
//        System.out.println("3 "+abbreviation("AbCdE", "AFE").equals("NO"));
//        System.out.println("4 "+abbreviation("beFgH", "EFG").equals("NO"));
//        System.out.println("5 "+abbreviation("beFgH", "EFH").equals("YES"));
//
//        System.out.println("6 "+abbreviation("Pi", "P").equals("YES"));
//        System.out.println("7 "+abbreviation("AfPZN", "APZNC").equals("NO"));
//        System.out.println("8 "+abbreviation("LDJAN", "LJJM").equals("NO"));
//        System.out.println("9 "+abbreviation("UMKFW", "UMKFW").equals("YES"));
//        System.out.println("10 "+abbreviation("KXzQ", "K").equals("NO"));
//        System.out.println("11 "+abbreviation("LIT", "LIT").equals("YES"));
//        System.out.println("12 "+abbreviation("QYCH", "QYCH").equals("YES"));
//        System.out.println("13 "+abbreviation("DFIQG", "DFIQG").equals("YES"));
//        System.out.println("14 "+abbreviation("sYOCa", "YOCN").equals("NO"));
//        System.out.println("15 "+abbreviation("beFgH", "EFH").equals("YES"));
//
//
//        System.out.println("16 "+abbreviation("LLZOSYAMQRMBTZXTQMQcKGLR", "LLZOSYAMBTZXMQKLR").equals("NO"));
//        System.out.println("17 "+abbreviation("MGYXKOVSMAHKOLAZZKWXKS", "MGXKOVSAHKOLZKKDP").equals("NO"));
//        System.out.println("18 "+abbreviation("VLKHNlpsrlrvfxftslslrrh", "VLKHN").equals("YES"));
//        System.out.println("19 "+abbreviation("OQSVONTNZMDJAVRZAZCVPKh", "OSVONTNZMDJAVRZAZCVPK").equals("NO"));
//        System.out.println("20 "+abbreviation("AXbosoh", "AX").equals("YES"));
//        System.out.println("21 "+abbreviation("EYONDOCHNZYYlBZXPGzX", "EYONDOCHNZYYBZXPGXOG").equals("NO"));
//        System.out.println("22 "+abbreviation("BJAFXKGENMFUvdsvcptrp", "BJAFXKGENMFU").equals("YES"));
//        System.out.println("23 "+abbreviation("UBUFOOSIXXsdtfmeyongkhehq", "UBUFOOSIXX").equals("YES"));
//        System.out.println("24 "+abbreviation("PWBIJLCOIAXGJGUXUZOutgic", "PWBIJLCOIAXGJGUXUZO").equals("YES"));
////        System.out.println(abbreviation("EOWZEOHWYOJTBNMcefdsp", "AX").equals("YES"));
//
//
//        //test case 6
//        System.out.println("6 1 "+abbreviation("RDWPJPAMKGRIWAPBZSYWALDBLDOFLWIQPMPLEMCJXKAENTLVYMSJNRJAQQPWAGVcGOHEWQYZDJRAXZOYDMNZJVUSJGKKKSYNCSFWKVNHOGVYULALKEBUNZHERDDOFCYWBUCJGbvqlddfazmmohcewjg", "RDPJPAMKGRIWAPBZSYWALDBLOFWIQPMPLEMCJXKAENTLVYMJNRJAQQPWAGVGOHEWQYZDJRAXZOYDMNZJVUSJGKKKSYNCSFWKVNHOGVYULALKEBUNZHERDOFCYWBUCJG").equals("NO"));
//        System.out.println("6 2 "+abbreviation("MBQEVZPBjcbswirgrmkkfvfvcpiukuxlnxkkenqp", "MBQEVZP").equals("NO"));
//        System.out.println("6 3 "+abbreviation("DINVMKSOfsVQByBnCWNKPRFRKMhFRSkNQRBVNTIKNBXRSXdADOSeNDcLWFCERZOLQjEZCEPKXPCYKCVKALNxBADQBFDQUpdqunpelxauyyrwtjpkwoxlrrqbjtxlkvkcajhpqhqeitafcsjxwtttzyhzvh", "DINVMKSOVQBBCWNKPRFRKMFRSNQRBVNTIKNBXRSXADOSNDLWFCERZOLQEZCEPKXPCYKCVKALNBADQBFDQU").equals("YES"));
//        System.out.println("6 4 "+abbreviation("BFZZVHdQYHQEMNEFFRFJTQmNWHFVXRXlGTFNBqWQmyOWYWSTDSTMJRYHjBNTEWADLgHVgGIRGKFQSeCXNFNaIFAXOiQORUDROaNoJPXWZXIAABZKSZYFTDDTRGZXVZZNWNRHMvSTGEQCYAJSFvbqivjuqvuzafvwwifnrlcxgbjmigkms","BFZZVHQYHQEMNEFFRFJTQNWHFVXRXGTFNBWQOWYWSTDSTMJRYHBNTEWADLHVGIRGKFQSCXNFNIFAXOQORUDRONJPXWZXIAABZKSZYFTDDTRGZXVZZNWNRHMSTGEQCYAJSF").equals("YES"));
//        System.out.println("6 5 "+abbreviation("AQIUQVIPJDKYNEBPXFGVHCMFGvURORPRSTYQYJZCYJDNFRPRYTMZIsNDOJAOAGAEFRCDKUJBhdkedalbwoxxnoyowoxpdlelovibyiwat", "AQIUQVIPJDKYNEBPXFGVHCMFGURORPRSTYQYJZCYJDNFRPRYTMZINDOJAOAGAEFRCDKUJB").equals("YES"));
//        System.out.println("6 6 "+abbreviation("HCPXJZTDXLWHYKHPPDFYFDJWTAETQLJCIIPVHMZHHOQTKONUHGYVKLXTFTBEMYAWXTCSwNJYALIGMIBDOWKIVStFATDOZCYSUCaATUWORPMTFPKTNHDSFWKRKBrXNBYICOZYDWLLElKKWTFAUSTZKFDCBQNYVcWKDHDMXJGFORwURHISYLBIZSOJXVRVBNPQLRJKIN", "HCPXJZTDXLWHYKHPPDFYFDJWTAETQLJCIIPVHMZHHOQTKONUHGYVKLXTFTBEMYAWXTCSNJYALIGMIBDOWKIVSFATDOZCYSUCATUWORPMTFPKTNHDSFWKRKBXNBYICOZYDWLLEKKWTFAUSTZKFDCBQNYVWKDHDMXJGFORURHISYLBIZSOJXVRVBNPQLRJKINIIOYB").equals("NO"));
//        System.out.println("6 7 "+abbreviation("IZLAKtDFAITDNWMVQPDShQQFGTRIXDLNBQPZRpuRJMLLPHBMOWrNagJDPPREZSYBHIWKDHLkjPSEUWIVQYUfPPJYKCbPEKCSKBRIAAJTMDPAOLNWSQESOTRQZOFTMTTGTDTrWLPENHXHLDWAFNDZMIFlogtcddtulusydquboxquwmgcji", "IZLAKDFAITDNWMVQPDSQQFGTRIXDLNBQPZRRJMLLPHBMOWNJDPPREZSYBHIWKDHLPSEUWIVQYUPPJYKCPEKCSKBRIAAJTMDPAOLNWSQESOTRQZOFTMTTGTDTWLPENHXHLDWAFNDZMIF").equals("YES"));
//        System.out.println("6 8 "+abbreviation("KRBPLVCTESRNPTCVNDMPTQYvFAWBGYPQHNXNAESRQMKFDZIEKVNZXSXKCFHQYCMMANPQFHWCEeNGOLWTUXZVMQNDZfRPLUFZcSTRLRYAZUKAZYXCVTNTNScSDFTBJSUKEQKZRDITZUCFVAPLCLTUWAXOnNHPYEOZDGWZPBJQBZEOFAeXTFJDWRHI", "KRBPVCTESRNPTCVNDMPTQYFWBGYPQHXNAESRQMFDZIEKVNZXSXKFHQYCMMANPQFHWCNGOLWTUXZVMQNDZRPLUFZSTRLRYAZUAZYXCVTNTNSSDTBJSUKEQKZRDITZUCFVAPCLTUWAXONHPYEOZDGWZPBJQBZEOAXTFJDWRHIPGQVCWODYNNV").equals("NO"));
//        System.out.println("6 9 "+abbreviation("WOAECAAVWMSQMIMYMAPEVARGIZCTIVNLAgydhmrxwcjltpjdewxhxrtynyyuyhqwbpkwuqtpwmyhemjxvwoazumyfstoumreirdkwbmepwbrgmyhjgtqeltzxnwhbunvuoejnhfqcikggaqjgsoqhzrmu", "WOAECAAVWMSQMIMYMAPEVARGIZCTIVNLA").equals("YES"));
//        System.out.println("6 10 "+abbreviation("RMPRWOBYTSjXGVJQPDQEHTWXMOGcHVWKATSWLBWPJBQTYKVHKMFKCYVVJXGLUEZTLSXChGBCAOAMiFEAPPAGWeMXXQAQTFCZGXKOGZLLUWTZDOYVWHIJZEIDOSHPwFWHYXCIZKTjKKVKQNDXMTCCBQMAGVCDPZOXHPSEQYthuqclzletakrqbzmaohadpog", "RMPRWOBYTSXGVJQPDQEHTWXMOGHVWKATSWLBWPJBQTYKVHKMFKCYVVJXGLUEZTLSXCGBCAOAMFEAPPAGWMXXQAQTFCZGXKOGZLLUWTZDOYVWHIJZEIDOSHPFWHYXCIZKTKKVKQNDXMTCCBQMAGVCDPZOXHPSEQY").equals("YES"));
//
//        System.out.println("6 11 "+abbreviation("BgGIRGKFQSeCXNFNaOiOaNoJPXWSZRHMvSFv", "BGIRGKFQSCXNFNOONJPXWSZRHMSF").equals("YES"));
//        System.out.println("6 12 "+abbreviation("BgirgkfqsGIRGKFQSeCXNFNaOiOaNoJPXWSZRHMvSFv", "BGIRGKFQSCXNFNOONJPXWSZRHMSF").equals("YES"));
//        System.out.println("6 13 "+abbreviation("BGgIRGKFQSeCXNFNaOiOaNoJPXWSZRHMvSFv", "BGIRGKFQSCXNFNOONJPXWSZRHMSF").equals("YES"));
//
//        System.out.println("11 1 "+abbreviation("bBccC", "BBC").equals("YES"));
//
//        System.out.println("11 2 "+abbreviation("bbccBBC", "BBC").equals("YES"));


        System.out.println(COUNT);
        //6 1 false
        //16,19 false


        //////////////////////////////////////////////////////////////
//        System.out.println("1 "+solution("AbcDe", "ABDE").equals("YES"));
//        System.out.println("2 "+solution("AbcDE", "AFDE").equals("NO"));
//
//        System.out.println("3 "+solution("AbCdE", "AFE").equals("NO"));
//        System.out.println("4 "+solution("beFgH", "EFG").equals("NO"));
//        System.out.println("5 "+solution("beFgH", "EFH").equals("YES"));
//
//        System.out.println("6 "+solution("Pi", "P").equals("YES"));
//        System.out.println("7 "+solution("AfPZN", "APZNC").equals("NO"));
//        System.out.println("8 "+solution("LDJAN", "LJJM").equals("NO"));
//        System.out.println("9 "+solution("UMKFW", "UMKFW").equals("YES"));
//        System.out.println("10 "+solution("KXzQ", "K").equals("NO"));
//        System.out.println("11 "+solution("LIT", "LIT").equals("YES"));
//        System.out.println("12 "+solution("QYCH", "QYCH").equals("YES"));
//        System.out.println("13 "+solution("DFIQG", "DFIQG").equals("YES"));
//        System.out.println("14 "+solution("sYOCa", "YOCN").equals("NO"));
//        System.out.println("15 "+solution("beFgH", "EFH").equals("YES"));
//
//
//        System.out.println("16 "+solution("LLZOSYAMQRMBTZXTQMQcKGLR", "LLZOSYAMBTZXMQKLR").equals("NO"));
//        System.out.println("17 "+solution("MGYXKOVSMAHKOLAZZKWXKS", "MGXKOVSAHKOLZKKDP").equals("NO"));
//        System.out.println("18 "+solution("VLKHNlpsrlrvfxftslslrrh", "VLKHN").equals("YES"));
//        System.out.println("19 "+solution("OQSVONTNZMDJAVRZAZCVPKh", "OSVONTNZMDJAVRZAZCVPK").equals("NO"));
//        System.out.println("20 "+solution("AXbosoh", "AX").equals("YES"));
//        System.out.println("21 "+solution("EYONDOCHNZYYlBZXPGzX", "EYONDOCHNZYYBZXPGXOG").equals("NO"));
//        System.out.println("22 "+solution("BJAFXKGENMFUvdsvcptrp", "BJAFXKGENMFU").equals("YES"));
//        System.out.println("23 "+solution("UBUFOOSIXXsdtfmeyongkhehq", "UBUFOOSIXX").equals("YES"));
//        System.out.println("24 "+solution("PWBIJLCOIAXGJGUXUZOutgic", "PWBIJLCOIAXGJGUXUZO").equals("YES"));
////        System.out.println(abbreviation("EOWZEOHWYOJTBNMcefdsp", "AX").equals("YES"));
//
//
//        //test case 6
//        System.out.println("6 1 "+solution("RDWPJPAMKGRIWAPBZSYWALDBLDOFLWIQPMPLEMCJXKAENTLVYMSJNRJAQQPWAGVcGOHEWQYZDJRAXZOYDMNZJVUSJGKKKSYNCSFWKVNHOGVYULALKEBUNZHERDDOFCYWBUCJGbvqlddfazmmohcewjg", "RDPJPAMKGRIWAPBZSYWALDBLOFWIQPMPLEMCJXKAENTLVYMJNRJAQQPWAGVGOHEWQYZDJRAXZOYDMNZJVUSJGKKKSYNCSFWKVNHOGVYULALKEBUNZHERDOFCYWBUCJG").equals("NO"));
//        System.out.println("6 2 "+solution("MBQEVZPBjcbswirgrmkkfvfvcpiukuxlnxkkenqp", "MBQEVZP").equals("NO"));
//        System.out.println("6 3 "+solution("DINVMKSOfsVQByBnCWNKPRFRKMhFRSkNQRBVNTIKNBXRSXdADOSeNDcLWFCERZOLQjEZCEPKXPCYKCVKALNxBADQBFDQUpdqunpelxauyyrwtjpkwoxlrrqbjtxlkvkcajhpqhqeitafcsjxwtttzyhzvh", "DINVMKSOVQBBCWNKPRFRKMFRSNQRBVNTIKNBXRSXADOSNDLWFCERZOLQEZCEPKXPCYKCVKALNBADQBFDQU").equals("YES"));
//        System.out.println("6 4 "+solution("BFZZVHdQYHQEMNEFFRFJTQmNWHFVXRXlGTFNBqWQmyOWYWSTDSTMJRYHjBNTEWADLgHVgGIRGKFQSeCXNFNaIFAXOiQORUDROaNoJPXWZXIAABZKSZYFTDDTRGZXVZZNWNRHMvSTGEQCYAJSFvbqivjuqvuzafvwwifnrlcxgbjmigkms","BFZZVHQYHQEMNEFFRFJTQNWHFVXRXGTFNBWQOWYWSTDSTMJRYHBNTEWADLHVGIRGKFQSCXNFNIFAXOQORUDRONJPXWZXIAABZKSZYFTDDTRGZXVZZNWNRHMSTGEQCYAJSF").equals("YES"));
//        System.out.println("6 5 "+solution("AQIUQVIPJDKYNEBPXFGVHCMFGvURORPRSTYQYJZCYJDNFRPRYTMZIsNDOJAOAGAEFRCDKUJBhdkedalbwoxxnoyowoxpdlelovibyiwat", "AQIUQVIPJDKYNEBPXFGVHCMFGURORPRSTYQYJZCYJDNFRPRYTMZINDOJAOAGAEFRCDKUJB").equals("YES"));
//        System.out.println("6 6 "+solution("HCPXJZTDXLWHYKHPPDFYFDJWTAETQLJCIIPVHMZHHOQTKONUHGYVKLXTFTBEMYAWXTCSwNJYALIGMIBDOWKIVStFATDOZCYSUCaATUWORPMTFPKTNHDSFWKRKBrXNBYICOZYDWLLElKKWTFAUSTZKFDCBQNYVcWKDHDMXJGFORwURHISYLBIZSOJXVRVBNPQLRJKIN", "HCPXJZTDXLWHYKHPPDFYFDJWTAETQLJCIIPVHMZHHOQTKONUHGYVKLXTFTBEMYAWXTCSNJYALIGMIBDOWKIVSFATDOZCYSUCATUWORPMTFPKTNHDSFWKRKBXNBYICOZYDWLLEKKWTFAUSTZKFDCBQNYVWKDHDMXJGFORURHISYLBIZSOJXVRVBNPQLRJKINIIOYB").equals("NO"));
//        System.out.println("6 7 "+solution("IZLAKtDFAITDNWMVQPDShQQFGTRIXDLNBQPZRpuRJMLLPHBMOWrNagJDPPREZSYBHIWKDHLkjPSEUWIVQYUfPPJYKCbPEKCSKBRIAAJTMDPAOLNWSQESOTRQZOFTMTTGTDTrWLPENHXHLDWAFNDZMIFlogtcddtulusydquboxquwmgcji", "IZLAKDFAITDNWMVQPDSQQFGTRIXDLNBQPZRRJMLLPHBMOWNJDPPREZSYBHIWKDHLPSEUWIVQYUPPJYKCPEKCSKBRIAAJTMDPAOLNWSQESOTRQZOFTMTTGTDTWLPENHXHLDWAFNDZMIF").equals("YES"));
//        System.out.println("6 8 "+solution("KRBPLVCTESRNPTCVNDMPTQYvFAWBGYPQHNXNAESRQMKFDZIEKVNZXSXKCFHQYCMMANPQFHWCEeNGOLWTUXZVMQNDZfRPLUFZcSTRLRYAZUKAZYXCVTNTNScSDFTBJSUKEQKZRDITZUCFVAPLCLTUWAXOnNHPYEOZDGWZPBJQBZEOFAeXTFJDWRHI", "KRBPVCTESRNPTCVNDMPTQYFWBGYPQHXNAESRQMFDZIEKVNZXSXKFHQYCMMANPQFHWCNGOLWTUXZVMQNDZRPLUFZSTRLRYAZUAZYXCVTNTNSSDTBJSUKEQKZRDITZUCFVAPCLTUWAXONHPYEOZDGWZPBJQBZEOAXTFJDWRHIPGQVCWODYNNV").equals("NO"));
//        System.out.println("6 9 "+solution("WOAECAAVWMSQMIMYMAPEVARGIZCTIVNLAgydhmrxwcjltpjdewxhxrtynyyuyhqwbpkwuqtpwmyhemjxvwoazumyfstoumreirdkwbmepwbrgmyhjgtqeltzxnwhbunvuoejnhfqcikggaqjgsoqhzrmu", "WOAECAAVWMSQMIMYMAPEVARGIZCTIVNLA").equals("YES"));
//        System.out.println("6 10 "+solution("RMPRWOBYTSjXGVJQPDQEHTWXMOGcHVWKATSWLBWPJBQTYKVHKMFKCYVVJXGLUEZTLSXChGBCAOAMiFEAPPAGWeMXXQAQTFCZGXKOGZLLUWTZDOYVWHIJZEIDOSHPwFWHYXCIZKTjKKVKQNDXMTCCBQMAGVCDPZOXHPSEQYthuqclzletakrqbzmaohadpog", "RMPRWOBYTSXGVJQPDQEHTWXMOGHVWKATSWLBWPJBQTYKVHKMFKCYVVJXGLUEZTLSXCGBCAOAMFEAPPAGWMXXQAQTFCZGXKOGZLLUWTZDOYVWHIJZEIDOSHPFWHYXCIZKTKKVKQNDXMTCCBQMAGVCDPZOXHPSEQY").equals("YES"));
//
//        System.out.println("6 11 "+solution("BgGIRGKFQSeCXNFNaOiOaNoJPXWSZRHMvSFv", "BGIRGKFQSCXNFNOONJPXWSZRHMSF").equals("YES"));
//        System.out.println("6 12 "+solution("BgirgkfqsGIRGKFQSeCXNFNaOiOaNoJPXWSZRHMvSFv", "BGIRGKFQSCXNFNOONJPXWSZRHMSF").equals("YES"));
//        System.out.println("6 13 "+solution("BGgIRGKFQSeCXNFNaOiOaNoJPXWSZRHMvSFv", "BGIRGKFQSCXNFNOONJPXWSZRHMSF").equals("YES"));
//
//        System.out.println("11 1 "+solution("bBccC", "BBC").equals("YES"));
//
//        System.out.println("11 2 "+solution("bbccBBC", "BBC").equals("YES"));


        ///////////////////////////////////////////////////////////
        //perfomance
//        System.out.println("10 1 "+solution("SGFRHHRTUNXWPSMCEPQVUMRFAPAGREOVDRAUEGIQMGIDEWDNZRTUKLFQFFNIYHZFXSRMNIFVYZCUIOUXPYILVDYZPJAMPJZWVHZOGJIDHUBSHGGAKMPVGCUVUUOQMXEEZSEQLJBAKMZDgxshpoqdprlsdtyyfagfltxdkhxtophvvkzvjxybzjyqcvqxilizrebbbgzqbcoqinrvyvsdrxgsieswsrbqxqalattwebmuviogrqhyjucdiqdbuplinbiegmfslcoxjoabaeomkbejibmjxqiogwkoupmgohvxdksnsdapfdghehpcenhlsxzxljvdtosgmzdeezvblqspvzlchkhnnjjevdciolawfqqixyorlbbgmcxmzukndgfztsjvqzjppwpgokygoqhwbexxnzivsvocsjcvlubinqgfrfbqagornokxauxjlucidtzmtpabttntxtdpcbtjmvfghhjtmquknzzeqmdueqxuoqhodochabdnorbnvjjjapqbuwagdmddgktfyirvctqumxvzahswtzoxsjxsmsydlpvkuchponglncfycqepjsqcawvuysxazalodlcfjrlzzbkplbtg", "SGFRHHRTUNXWPSMCEPQVUMRFAPAGREOVDRAUEGIQMGIDEWDNZRTUKLFQFFNIYHZFXSRMNIFVYZCUIOUXPYILVDYZPJAMPJZWVHZOGJIDHUBSHGGAKMPVGCUVUUOQMXEEZSEQLJBAKMZD").equals("YES"));
//        System.out.println("10 2 "+solution("RvIBYSLJgMCUXJZVGOWRYHRCKAxMTFlSNXtAOFHDVDJGAAUEHYkPYKlFJjUuiKUQAlGJNFYKDPUgGKGWJNCgWBMDWJAZROLSLCZFBEQTDSKETJLVZydMERSZAOLMZABPHePThHGWROMFYFFQoXFZKBPHMWTMYHWJMpIpgTZHtSUUKaCFPYRjORTTKEVFZSHDNvLAISQmSSCIDFQYSJLMDTIMWPMEJPMGNPPRQMYQZSMJPTFYZGFPUJNHTUYZUXACIRIGPGOQWYSCFRCGGBLBLQUPZPUWXDWQDGPPCAFPSOClGuSYCTnvEGEKYZHgrbohrjprwokqfrsrcymttgifrythmtkxtxezjszuhoggqcnbsgevmpdrufwmhlabgkdstktbfizpstvdpzempmoivhlmwroaeihlfgpodyonbvmxhrqygvrzvrzkltmdolpwfxeyifyciljfscypfwfoalvcwzvgmkifxfkbhhlbipoidafpivrznbmtpyeepdcpxdokbyoonutwtqibbjtvwpgqfftedkuinfesrljtkofqkjvpysxygpblyfycvwxghykzqyssacrietwndasbpgiclnkbdrflydferrenlfdoecwpjwufifsemvrbubmrdqcsrgylglvrvsojpreoyapuucbulelnwxrgaaxillmnytnxbyrjqfokprdflfzikyutznhfqoylvmlcuzhqxiurdawzjyyqbvikcnchbztjbymygbudcjymikyccbpoiavwkbedeywswjhjavehitrphohfpdpwjlorpbhsjcifxrvykhljwawrtkafleinjknycatywwfgieacfqqpbwesgbzbpxiluxsolyhgnmbssunvndmczosrcssqsocxofuqaxxqqdfayqoeyrjpakiledsjnzruzekdshisxklpbqqxoyohbfovhfmygudepsktmgtboxugqqcy", "RIBYSLJMCUXJZVGOWRYHRCKAMTFSNXAOFHDVDJGAAUEHYPYKFJUKUQAGJNFYKDPUGKGWJNCWBMDWJAZROLSLCZFBEQTDSKETJLVZMERSZAOLMZABPHPTHGWROMFYFFQXFZKBPHMWTMYHWJMITZHSUUKCFPYRORTTKEVFZSHDNLAISQSSCIDFQYSJLMDTIMWPMEJPMGNPPRQMYQZSMJPTFYZGFPUJNHTUYZUXACIRIGPGOQWYSCFRCGGBLBLQUPZPUWXDWQDGPPCAFPSOCGSYCTEGEKYZH").equals("YES"));
//
//        System.out.println("10 3 "+solution("SNQLMGOmCbVHLMKSJOSOLDNLAVERGNZUXGHOGBUXHHGOCECNCXBzIJmQCCKPCEUAOcZNDKZEHEBDHEOLBLUTAUgKDHNJGHMFEBWASKIBERPCBPJGFFyHDYFWYUGzQTCvGQFJDrPJFPMTUKBsXPVXNKTDQRRRPPVDWFRhCoyWIYUPNADZerFSQDGCtqGVVPWMZVNUWUMMBBPSBZQGESUIMXEUCMEBGGKLGDHVPPOMLXOUFWZENPBPKVkVYATLMOXvZTXVWHLYGIDSEPCHRXZYNTFCFFuQGYSETXNKUgITLxXCNUGJMaPQNrQYUNOOPKbXNMgDSFLFBBSTNKvZENUUPWONLJFHBKNARBBNLTCTKFzVUAODEFQBfRGRMPuXQYGFPVNUGSDRNFMAEKDQHoGoGXBJLWRBAIACKCuCOALIWUvTdVhOKLYXFUIFytNQSIIsPTKKTBBADTBJRUHRBQGPNZLLCMDDYPWXQURFEDQZLdODSIZBNIADVjLsLENGMLBTtWLMRLBpBVBNSMYTQMOUAFMPDUVEBTJWBRXPKNRDTLBQYCUyKZHRWASHPVzYXLTSDYNvYLMMHWOXCLRXAMTPqRAoPZSGZFiFFRgTMROZULQSVypFRTJQKIRXFRbQTHSCVQBqWACWPCCNbBPZPCLzTRJQHUPEZiWBTZWWQWRUUOmKJCyQVTRCNRIHPRPKOEIgChEISVBGJRWLSRIBGzFMGHXYMLPQWUPOXGVGPOQHRVUJJWLNWBlDMHTLXVDIOFHULTAVdjAXASXMUJYNIPWOJcQFAOCBXQADGKMHMHUoSWMQVLYQSTMYYZtypTTSVGZQGZCFcNYNSBZFNMIhjGiTNWQCTGnYVSINYJvPkeGJFtFKKUPICFHOTUNFpE", "XIPPYUARLQTCXSVQYXYTVAIAGNWUIKCYVMRWSQPDBMTXMXMMZTTKGTBSHWLOOCNJLZZFZZPZHBGYOUNSHJQEXAPBXTZIMSNQLMGOCVHLMKSJOSOLDNLAVERGNZUXGHOGBUXHHGOCECNCXBIJQCCKPCEUAOZNDKZEHEBDHEOLBLUTAUKDHNJGHMFEBWASKIBERPCBPJGFFHDYFWYUGQTCGQFJDPJFPMTUKBXPVXNKTDQRRRPPVDWFRCWIYUPNADZFSQDGCGVVPWMZVNUWUMMBBPSBZQGESUIMXEUCMEBGGKLGDHVPPOMLXOUFWZENPBPKVVYATLMOXZTXVWHLYGIDSEPCHRXZYNTFCFFQGYSETXNKUITLXCNUGJMPQNQYUNOOPKXNMDSFLFBBSTNKZENUUPWONLJFHBKNARBBNLTCTKFVUAODEFQBRGRMPXQYGFPVNUGSDRNFMAEKDQHGGXBJLWRBAIACKCCOALIWUTVOKLYXFUIFNQSIIPTKKTBBADTBJRUHRBQGPNZLLCMDDYPWXQURFEDQZLODSIZBNIADVLLENGMLBTWLMRLBBVBNSMYTQMOUAFMPDUVEBTJWBRXPKNRDTLBQYCUKZHRWASHPVYXLTSDYNYLMMHWOXCLRXAMTPRAPZSGZFFFRTMROZULQSVFRTJQKIRXFRQTHSCVQBWACWPCCNBPZPCLTRJQHUPEZWBTZWWQWRUUOKJCQVTRCNRIHPRPKOEICEISVBGJRWLSRIBGFMGHXYMLPQWUPOXGVGPOQHRVUJJWLNWBDMHTLXVDIOFHULTAVAXASXMUJYNIPWOJQFAOCBXQADGKMHMHUSWMQVLYQSTMYYZTTSVGZQGZCFNYNSBZFNMIGTNWQCTGYVSINYJPGJFFKKUPICFHOTUNFELFGSKLWSAKHVRASPJKDWLVVCGCCZRBMGRMJXHNJCZOCQVVIDCXZOSUJWMARACWDCTQOXWDJUOTUXZMGORHBMPWSXK").equals("NO"));
//
//        System.out.println("10 4 "+solution("JSKKKPVEIKELNYFFaAPIFjzzswzguxgyxtfwihsbbrbnhqrqfhvilbhisifdfymuhnjpeplqxhgygbrmxkqvavhpvzupyfarttbavieetuqgokibzwriaroxyxuflxhftzzydpilikmdsxwlcfsshpmshhselchirblbkjutgctiwdoesgxhnfobwhsavehtvmjudlvkkkxowynjrufqvmczkeuktlhxvgzwcceguelipbtredjgcuhyuzuvvtkljlnfdjkouwbykkiyuqdymyvcmxzshdcnihvpxdjsrmeztshijnalnxfckrrpeppfpgmxtkinylgnkgnhorrfjdozdjtntoovqfdrvxzvsbsdyibkkimydxjpiagtydkyfzkdhtzorwosdtrxhraxqdzgtokthxerbcufawndvmwcjayonhldszdytfzdfbztdhzdylgokvulgmeadoivxzirhnncipyswsvvawwzqtinowejyspwgxvfzdwyoysqaqmhmlgedvckvaetggxukonuhzkfvvvrzxdpioffcreanvtyhkulxejdgxxxdlzwosuehzyhthezisipyoeibicozjpkglntmqkaaxalpfapgsiykkhcibyqmjoxxjgipprjfwabdncyhcutsitqzkadaufsactektrwqvjdpqgyjlvpiwyxfkgteyfffzefxngqctmntytwhgywqamfwtdkebujupwvcbtrdrmpshpztdehtxdleidscvhrariknfeumocebntrnrcmujrykinldwtvopxzqpkmtansbatxeffxqirysemxygcokgvafrdyegwnuowtqxywhilocfltbfnvtjcvhbtjitacqqqgdcvdlvmzmdbqxaemppntrtpzpchlqcohpqjrfecvufzkwzxmkdxsswbeyqkhluhhwlqofvybcqufcuwyhbdnyemjcpvqngfy", "JSKKKPVEIKELNYFFAPIF").equals("YES"));
//
//        System.out.println("10 5 "+solution("OUXjOCIQXENWIDEQHPGAYzZTBRNgKYYUFFXMTPRQZLqBDWQGlkCMGElBESUJRWhSTMSACGBCAEHFKIgTJWIoWTRGPGAMSUFNVQJtICRSLKMKBYQZBXEDASNQXIPWQNDTZUPVTEPYVVHPTSKWEWdsXQMXSDTOVGXRTBEINGFAIZOXUHNKEIBHULPRTXEZPRUTWOFHYjZKHXPDHGTQVDGCHLDWLuMPQGQGKXFSCUVUDRLyEGEBGIMXRDBTKQWBLBQtXHKTMXBGANAESDZWIKYCOqWYADfSWRHFLSLZFURQMYOOAYCPOYSNFRLQSULKCLTVOBSLUUTXOXYhHAKCZIFPTUQMFJAmIBkLSEVuEOCRHBZLVSdSZXAATLMZGHPyMRSFXOLLJUJNRYEDVIEFVXEXGAAWTAQIVDDLCLBYCEMBKZEGPXJVFOCGNVZCOKINPHDADLEdVLYURGEVCJLxDTIWFYAQQNASMZLIUJXBNWMSPxDWCjxEZIRODAKNMPFKRmYWPKFUAAPJEZHEUXKCDMVBGSRNYEYAFBCVIVlEBXMVUYlFPBLAMJFLATXKRUQHCZKAQKFBROFpyCWZSCWCUtQDHYIFYNWNNKLsITFUGLUDEQWEFDHWQYtWQGNBYXQUIEMZQEKXMSaVEGVOADUYVNOGLLSCL", "OUXOCIQXENWIDEQHPGAYZTBRNKYYUFFXMTPRQZLBDWQGCMGEBESUJRWSTMSACGBCAEHFKITJWIWTRGPGAMSUFNVQJICRSLKMKBYQZBXEDASNQXIPWQNDTZUPVTEPYVVHPTSKWEWXQMXSDTOVGXRTBEINGFAIZOXUHNKEIBHULPRTXEZPRUTWOFHYZKHXPDHGTQVDGCHLDWLMPQGQGKXFSCUVUDRLEGEBGIMXRDBTKQWBLBQXHKTMXBGANAESDZWIKYCOWYADSWRHFLSLZFURQMYOOAYCPOYSNFRLQSULKCLTVOBSLUUTXOXYHAKCZIFPTUQMFJAIBLSEVEOCRHBZLVSSZXAATLMZGHPMRSFXOLLJUJNRYEDVIEFVXEXGAAWTAQIVDDLCLBYCEMBKZEGPXJVFOCGNVZCOKINPHDADLEVLYURGEVCJLDTIWFYAQQNASMZLIUJXBNWMSPDWCEZIRODAKNMPFKRYWPKFUAAPJEZHEUXKCDMVBGSRNYEYAFBCVIVEBXMVUYFPBLAMJFLATXKRUQHCZKAQKFBROFCWZSCWCUQDHYIFYNWNNKLITFUGLUDEQWEFDHWQYWQGNBYXQUIEMZQEKXMSVEGVOADUYVNOGLLSCLTDHMALBIOGTUHCV").equals("NO"));
//        System.out.println("10 6 "+solution("HAAFVPIFcQJQNPRMSFCHJTWOnVDFUjYDQqMYEGIZFIXVWCVMOXUEYTBSQIBKFUJMEEKHQFZCUGFYTKehLBNeEAJYlAHKYBvILQEKUYHAZEDYdvSCPWNIDOFvYOZLASZBWFGBiQPHDNDYUTFVBBIIWzNQUNTZwKOKNIWJOFRvMEOYYBWYFYIETZBRIIDIQSDBDCHCTSEDQBUQDVZERBXTbIBMROJAISSPVBRTHwiVTDOFBEJVNGRjMEMjTXQSARAJGGjDTCKEKCCPPKXPNCXEDEMVGWPNUWLLEFHmWKZGDOMOHVHJWQSeTMXXDJABJNPSsBKHCFGUKOSEqOSGITXPQOJWVGIVwFKGmCMLHWAASBIUWPLBNKLEYNOAVVSUIDLSFWGZEOYXOWYTNGHPFOFUVMGVCDSFGPHQANImLQBTTtKSACVRGiONMZVLdLKAlRSIVCGBFWPSQYWcJsMMZNRTBJCRKCReOAVBZWKiNWKFKTOHDNYMGaJOXiWeKPKKJTKPpLMNWXCEUKYLoYESQPvGXNNQNWAFMWYIOZAMMQKGAXRTVlVFMRPDFFDXNKgDnbbkgyaropqrsuhtdpdyhwscgfnqDudqkzyeviskmbbxskojyakluqzqiizjgycdtrifvolgjtgrxerpt", "HAAFVPIFQJQNPRMSFCHJTWOVDFUYDQMYEGIZFIXVWCVMOXUEYTBSQIBKFUJMEEKHQFZCUGFYTKLBNEAJYAHKYBILQEKUYHAZEDYSCPWNIDOFYOZLASZBWFGBQPHDNDYUTVBBIIWNQUNTZKOKNIWJOFREOYYBWYFYTZBRIIDIQSDBDCHCTSEDQBUQDVZERBXTIBMROJAISSPVBRTHVTDOFBEJVNGRMEMTXQSARAJGGDTCKEKCCPPKXPNCXEDEMVGWPNUWLLEFHWKZGDOMOHVHWQSTMXXDJABJNPSBKHCFGUKOEOSGITXPQOJWVGIVFKGCMLHWAASBIUWPLBNKLEYNOAVVSUIDLSFWGZEOYXOWYTNGHPFOFUVMGVCDSFGPHQNILQBTTKSACVRGONMZVLLKARSIVCGBFWPSQYWJMZNRTBJCRKCROAVBZWKNWKFKTOHDNYMGJOXWKPKKJTKPLMNWXCEUKYLYESQPGXNNQNWAFMWYIOZAMMQKGAXRTVVFMRPDFFDXNKD").equals("NO"));
//        System.out.println("10 7 "+solution("EXXOSNDSERPFBOTCHTzEGDERRzaKRXGXMzZORuEIBKBQYNPBKFLZIJGwSHMARbOYXAJBEIZDbADDZFDSEZkEPDLYFWHWiYTDDNEURIpUBSPZMSULPWOWMULPYJELLfGNVNJtRGMWYBTGAMHdXHITMNKVLXGFZNPDGKCSMGTSbORIACMKMYZUNOWPXMZUKVEsFGUMTWfDDGpXZRFYNfKAUUQTHOnWAHLBRKEKBOZFULHFIKJVSKWWRAZLCBZZTWQEABOCJDLOLUHCeEPAtBMYXFVUVKVNGNSWLiZTQUAJGQNGQOSGUOoFELZKFDAPGACYMUYwGEFLFYLWrAXTAwAyREMIFtCMRAHCDOEGTSSxQzJSFLRKONKJEEHXESnSHXVOERNGLUZMFTXMLDlGSYVrOKBzZZDVgQYTNTUSUTYPWKXTGVFGVPPQSUTYTGMBEMCHCLPCfZOTQFPFGDTIUDJEeODOQYKYMWYZWQeMVNWZxXWFMRQEPUWMFRpYLINLTLJLmlKOUWEXVYeLPNZXJVTHHNMlSRTAUfDREDBAQPLOMCTVfOEUOMCICZSHaDYYVRsOSZJQTAJeKOWTJQMxNMrNOOONEWWSPIJAZYTVZVXONQEIODCDWPUXUIAXHMLTYkBYSYMGAWUQObHBfJPXPLKTXNDUPHXEMBOBYJQFXqBEeNUlWUESYNGFBTFAYEUIHbAGVWHBSTANWKYFdUhjKkGGXZBKFOAYWKXIcKAWXIZUOSTKCLMFXgNYhRUMQDNKTkQIXGANZDMMGTupFOdGCPEWIGJXLNNKcPsXZJRFTBKZMZFQuKVQVJFRZnCMGcXsAZABLnLNBVGTZXDPHHBLPLaHUMKMRAeOZrZVeCGCTGTMZKGCCHFjNKQEJmARBLLGcXYRPBBJNMERKXBOSdQTZTAOZEdPKOZkLOBCLVURFAYPMPHMEXSGONHANYNAEBAUNPFCOVKZGH", "EXXOSNDSERPFBOTCHTEGDERRKRXGXMZOREIBKBQYNPBKFLZIJGSHMAROYXAJBEIZDADDZFDSEZEPDLYFWHWYTDDNEURIUBSPZMSULPWOWMULPYJELLGNVNJRGMWYBTGAMHXHITMNKVLXGFZNPDGKCSMGTSORIACMKMYZUNOWPXMZUKVEFGUMTWDDGXZRFYNKAUUQTHOWAHLBRKEKBOZFULHFIKJVSKWWRAZLCBZZTWQEABOCJDLOLUHCEPABMYXFVUVKVNGNSWLZTQUAJGQNGQOSGUOFELZKFDAPGACYMUYGEFLFYLWAXTAAREMIFCMRAHCDOEGTSSQJSFLRKONKJEEHXESSHXVOERNGLUZMFTXMLDGSYVOKBZZDVQYTNTUSUTYPWKXTGVFGVPPQSUTYTGMBEMCHCLPCZOTQFPFGDTIUDJEODOQYKYMWYZWQMVNWZXWFMRQEPUWMFRYLINLTLJLKOUWEXVYLPNZXJVTHHNMSRTAUDREDBAQPLOMCTVOEUOMCICZSHDYYVROSZJQTAJKOWTJQMNMNOOONEWWPIJAZYTVZVXONQEIODCDWPUXUIAXHMLTYBYSYMGAWUQOHBJPXPLKTXNDUPHXEMBOBYJQFXBENUWUESYNGFBTFAYEUIHAGVWHBSTANWKYFUKGGXZBKFOAYWKXIKAWXIZUOSTKCLMFXNYRUMQDNKTQIXGANZDMMGTFOGCPEWIGJXLNNKPXZJRFTBKZMZFQKVQVJFRZCMGXAZABLLNBVGTZXDPHHBLPLHUMKMRAOZZVCGCTGTMZKGCCHFNKQEJARBLLGXYRPBBJNMERKXBOSQTZTAOZEPKOZLOBCLVURFAYPMHMEXSGONHANYNAEBAUNPFCOVKZGHYDEXQBJRIGIFPIBPEKKWEANPLVMRJEBHGGATMSJCXXOKKTAZCURCWBFPCPBOHVDY").equals("NO"));
//
//        System.out.println("10 8 "+solution("NOYXBKBVJBDAHEJWFGJKAZZWWSMLGDKSOAEMMFBYGUCBFPfGSAIQBAFNXPEOEUQPIALNmGMXUJVLOMAQYVEWYZBPLHZHWBKVZZXQHVJINHVOTGCLGMTLMLGXAOSWHILCQJVUMXGJRQKKFLULMSPVSDNVGJEIGRBVFkPMGZSIRADSQNDLWBPAFNKQAAPYOYEEGWAQNXSOCPWSJOTDCXQRGLHKeAWJAMBWMFUURHrNXTYFOLKNHKGvDJNOBONPGoKZUMFVFCJCYGFMLSDPPFNFIJINMBaEKXDKIFCmPRFKCLZILMBXZFZCFQHVZHJCILSZKpRDGSYLAXPTHJIHWHEJGDWJDHBNVIMLDDNYUKQLIJZXIRTIHFOXWPSUFuYEHTQMNSMIYUKZHUHDUSNPLIUPHMYPQHBWOBJYOKOgBUJYBBYJQOMZNOPEGAgOMAPJIWMyAFSzsQRJKJPUOAYCDEkOUHTUKmEEDXWSZqZXEZWYPBCOUQYhVMWiKARFKZMDLdFVVVKIHHJLPAZFCKKHKUONETXRXZOOimksumyzvdumiuitojcwhuitmslsmiioua", "NOYXBKBVJBDAHEJWFGJKAZZWWSMLGDKSOAEMMFBYGUCBFPGSAIQBAFNXPEOEUQPIALNGMXUJVLOMAQYVEWYZBPLHZHWBKVZZXQHVJINHVOTGCLGMTLMLGXAOSWHILCQJVUMXGJRQKKFLULMSPVSDNVGJEIGRBVFPMGZSIRADSQNDLWBPAFNKQAAPYOYEEGWAQNXSOCPWSJOTDCXQRGLHKAWJAMBWMFUURHNXTYFOLKNHKGDJNOBONPGKZUMFVFCJCYGFMLSDPPFNFIJINMBEKXDKIFCPRFKCLZILMBXZFZCFQHVZHJCILSZKRDGSYLAXPTHJIHWHEJGDWJDHBNVIMLDDNYUKQLIJZXIRTIHFOXWPSUFYEHTQMNSMIYUKZHUHDUSNPLIUPHMYPQHBWOBJYOKOBUJYBBYJQOMZNOPEGAOMAPJIWMAFSQRJKJPUOAYCDEOUHTUKEEDXWSZZXEZWYPBCOUQYVMWKARFKZMDLFVVVKIHHJLPAZFCKKHKUONETXRXZOO").equals("YES"));
//        System.out.println("10 9 "+solution("JZMHWRAMQlPDZCHACDSZRBBDRFNYXSrMBRMRPFGFJKUAKXZIZNTPQTKWWXBHDRKGAXBJAIKXUOZJTCPPvWzKNSDGBDPAZDOXEPDEuTQsIEHBBRKCJHITUYSFNyAOIyHGHOHTGAMWOVVPPUXJOLLXSRIZVDJQUGOQESLQWQCPGIAAOKEBGGBAPJQZCQKGNSWSLJNKOATNCRMIQQaIKTREJCJKKOGGSVQLIXGvcnyhjbysbsidiaxijmscpvpxcnobttukhbcftlplathovfffllyqkig", "JZMHWRAMQPDZCHACDSZRBBDRFNYXSMBRMRPFGFJKUAKXZIZNTPQTKWWXBHDRKGAXBJAIKXUOZJTCPPWKNSDGBDPAZDOXEPDETQIEHBBRKCJHITUYSFNAOIHGHOHTGAMWOVVPPUXJOLLXSRIZVDJQUGOQESLQWQCPGIAAOKEBGGBAPJQZCQKGNSWSLJNKOATNCRMIQQIKTREJCJKKOGGSVQLIXG").equals("YES"));
//        System.out.println("10 10"+solution("TFPUBEUYDRYZNVNHITXXTHHVPPJXGBIMTQHZTMFYAQREVIVQWMIQOGDVFZGOPJVNQCDNFHOOJLPYNWRUIBUFVFCMJGDKGIPCYYAUFLXKYUZXUAXRUGMAAOCDHOJHBDSPLGVEXFUYEEUOFTWTCWFBSOHDVAOKGLVHSFGOBJDLTFKIOTQIISKXFOXEEFPOAPWXLAAPFEFTfcjxjvnqzldhdfgzipiihgrvdhbajorwprykrfbdsqzykvlvcnuegjnkzjyvcdrtfbjgubizwvcqwyyvnhggmawcseeejpixdotsiuxylzyondkuhixhrelfvoyregccztonhedogzawsdzssuydhacfyhwwyuzrcjuontcyqjrlzchgwpdtnevjmqiuifrypupwlugahvrthufedc", "TFPUBEUYDRYZNVNHITXXTHHVPPJXGBIMTQHZTMFYAQREVIVQWMIQOGDVFZGOPJVNQCDNFHOOJLPYNWRUIBUFVFCMJGDKGIPCYYAUFLXKYUZXUAXRUGMAAOCDHOJHBDSPLGVEXFUYEEUOFTWTCWFBSOHDVAOKGLVHSFGOBJDLTFKIOTQIISKXFOXEEFPOAPWXLAAPFEFT").equals("YES"));


        ////////////////////
        System.out.println("10 1 " + abbreviation("SGFRHHRTUNXWPSMCEPQVUMRFAPAGREOVDRAUEGIQMGIDEWDNZRTUKLFQFFNIYHZFXSRMNIFVYZCUIOUXPYILVDYZPJAMPJZWVHZOGJIDHUBSHGGAKMPVGCUVUUOQMXEEZSEQLJBAKMZDgxshpoqdprlsdtyyfagfltxdkhxtophvvkzvjxybzjyqcvqxilizrebbbgzqbcoqinrvyvsdrxgsieswsrbqxqalattwebmuviogrqhyjucdiqdbuplinbiegmfslcoxjoabaeomkbejibmjxqiogwkoupmgohvxdksnsdapfdghehpcenhlsxzxljvdtosgmzdeezvblqspvzlchkhnnjjevdciolawfqqixyorlbbgmcxmzukndgfztsjvqzjppwpgokygoqhwbexxnzivsvocsjcvlubinqgfrfbqagornokxauxjlucidtzmtpabttntxtdpcbtjmvfghhjtmquknzzeqmdueqxuoqhodochabdnorbnvjjjapqbuwagdmddgktfyirvctqumxvzahswtzoxsjxsmsydlpvkuchponglncfycqepjsqcawvuysxazalodlcfjrlzzbkplbtg", "SGFRHHRTUNXWPSMCEPQVUMRFAPAGREOVDRAUEGIQMGIDEWDNZRTUKLFQFFNIYHZFXSRMNIFVYZCUIOUXPYILVDYZPJAMPJZWVHZOGJIDHUBSHGGAKMPVGCUVUUOQMXEEZSEQLJBAKMZD").equals("YES"));
        System.out.println("10 2 " + abbreviation("RvIBYSLJgMCUXJZVGOWRYHRCKAxMTFlSNXtAOFHDVDJGAAUEHYkPYKlFJjUuiKUQAlGJNFYKDPUgGKGWJNCgWBMDWJAZROLSLCZFBEQTDSKETJLVZydMERSZAOLMZABPHePThHGWROMFYFFQoXFZKBPHMWTMYHWJMpIpgTZHtSUUKaCFPYRjORTTKEVFZSHDNvLAISQmSSCIDFQYSJLMDTIMWPMEJPMGNPPRQMYQZSMJPTFYZGFPUJNHTUYZUXACIRIGPGOQWYSCFRCGGBLBLQUPZPUWXDWQDGPPCAFPSOClGuSYCTnvEGEKYZHgrbohrjprwokqfrsrcymttgifrythmtkxtxezjszuhoggqcnbsgevmpdrufwmhlabgkdstktbfizpstvdpzempmoivhlmwroaeihlfgpodyonbvmxhrqygvrzvrzkltmdolpwfxeyifyciljfscypfwfoalvcwzvgmkifxfkbhhlbipoidafpivrznbmtpyeepdcpxdokbyoonutwtqibbjtvwpgqfftedkuinfesrljtkofqkjvpysxygpblyfycvwxghykzqyssacrietwndasbpgiclnkbdrflydferrenlfdoecwpjwufifsemvrbubmrdqcsrgylglvrvsojpreoyapuucbulelnwxrgaaxillmnytnxbyrjqfokprdflfzikyutznhfqoylvmlcuzhqxiurdawzjyyqbvikcnchbztjbymygbudcjymikyccbpoiavwkbedeywswjhjavehitrphohfpdpwjlorpbhsjcifxrvykhljwawrtkafleinjknycatywwfgieacfqqpbwesgbzbpxiluxsolyhgnmbssunvndmczosrcssqsocxofuqaxxqqdfayqoeyrjpakiledsjnzruzekdshisxklpbqqxoyohbfovhfmygudepsktmgtboxugqqcy", "RIBYSLJMCUXJZVGOWRYHRCKAMTFSNXAOFHDVDJGAAUEHYPYKFJUKUQAGJNFYKDPUGKGWJNCWBMDWJAZROLSLCZFBEQTDSKETJLVZMERSZAOLMZABPHPTHGWROMFYFFQXFZKBPHMWTMYHWJMITZHSUUKCFPYRORTTKEVFZSHDNLAISQSSCIDFQYSJLMDTIMWPMEJPMGNPPRQMYQZSMJPTFYZGFPUJNHTUYZUXACIRIGPGOQWYSCFRCGGBLBLQUPZPUWXDWQDGPPCAFPSOCGSYCTEGEKYZH").equals("YES"));

        System.out.println("10 3 " + abbreviation("SNQLMGOmCbVHLMKSJOSOLDNLAVERGNZUXGHOGBUXHHGOCECNCXBzIJmQCCKPCEUAOcZNDKZEHEBDHEOLBLUTAUgKDHNJGHMFEBWASKIBERPCBPJGFFyHDYFWYUGzQTCvGQFJDrPJFPMTUKBsXPVXNKTDQRRRPPVDWFRhCoyWIYUPNADZerFSQDGCtqGVVPWMZVNUWUMMBBPSBZQGESUIMXEUCMEBGGKLGDHVPPOMLXOUFWZENPBPKVkVYATLMOXvZTXVWHLYGIDSEPCHRXZYNTFCFFuQGYSETXNKUgITLxXCNUGJMaPQNrQYUNOOPKbXNMgDSFLFBBSTNKvZENUUPWONLJFHBKNARBBNLTCTKFzVUAODEFQBfRGRMPuXQYGFPVNUGSDRNFMAEKDQHoGoGXBJLWRBAIACKCuCOALIWUvTdVhOKLYXFUIFytNQSIIsPTKKTBBADTBJRUHRBQGPNZLLCMDDYPWXQURFEDQZLdODSIZBNIADVjLsLENGMLBTtWLMRLBpBVBNSMYTQMOUAFMPDUVEBTJWBRXPKNRDTLBQYCUyKZHRWASHPVzYXLTSDYNvYLMMHWOXCLRXAMTPqRAoPZSGZFiFFRgTMROZULQSVypFRTJQKIRXFRbQTHSCVQBqWACWPCCNbBPZPCLzTRJQHUPEZiWBTZWWQWRUUOmKJCyQVTRCNRIHPRPKOEIgChEISVBGJRWLSRIBGzFMGHXYMLPQWUPOXGVGPOQHRVUJJWLNWBlDMHTLXVDIOFHULTAVdjAXASXMUJYNIPWOJcQFAOCBXQADGKMHMHUoSWMQVLYQSTMYYZtypTTSVGZQGZCFcNYNSBZFNMIhjGiTNWQCTGnYVSINYJvPkeGJFtFKKUPICFHOTUNFpE", "XIPPYUARLQTCXSVQYXYTVAIAGNWUIKCYVMRWSQPDBMTXMXMMZTTKGTBSHWLOOCNJLZZFZZPZHBGYOUNSHJQEXAPBXTZIMSNQLMGOCVHLMKSJOSOLDNLAVERGNZUXGHOGBUXHHGOCECNCXBIJQCCKPCEUAOZNDKZEHEBDHEOLBLUTAUKDHNJGHMFEBWASKIBERPCBPJGFFHDYFWYUGQTCGQFJDPJFPMTUKBXPVXNKTDQRRRPPVDWFRCWIYUPNADZFSQDGCGVVPWMZVNUWUMMBBPSBZQGESUIMXEUCMEBGGKLGDHVPPOMLXOUFWZENPBPKVVYATLMOXZTXVWHLYGIDSEPCHRXZYNTFCFFQGYSETXNKUITLXCNUGJMPQNQYUNOOPKXNMDSFLFBBSTNKZENUUPWONLJFHBKNARBBNLTCTKFVUAODEFQBRGRMPXQYGFPVNUGSDRNFMAEKDQHGGXBJLWRBAIACKCCOALIWUTVOKLYXFUIFNQSIIPTKKTBBADTBJRUHRBQGPNZLLCMDDYPWXQURFEDQZLODSIZBNIADVLLENGMLBTWLMRLBBVBNSMYTQMOUAFMPDUVEBTJWBRXPKNRDTLBQYCUKZHRWASHPVYXLTSDYNYLMMHWOXCLRXAMTPRAPZSGZFFFRTMROZULQSVFRTJQKIRXFRQTHSCVQBWACWPCCNBPZPCLTRJQHUPEZWBTZWWQWRUUOKJCQVTRCNRIHPRPKOEICEISVBGJRWLSRIBGFMGHXYMLPQWUPOXGVGPOQHRVUJJWLNWBDMHTLXVDIOFHULTAVAXASXMUJYNIPWOJQFAOCBXQADGKMHMHUSWMQVLYQSTMYYZTTSVGZQGZCFNYNSBZFNMIGTNWQCTGYVSINYJPGJFFKKUPICFHOTUNFELFGSKLWSAKHVRASPJKDWLVVCGCCZRBMGRMJXHNJCZOCQVVIDCXZOSUJWMARACWDCTQOXWDJUOTUXZMGORHBMPWSXK").equals("NO"));

        System.out.println("10 4 " + abbreviation("JSKKKPVEIKELNYFFaAPIFjzzswzguxgyxtfwihsbbrbnhqrqfhvilbhisifdfymuhnjpeplqxhgygbrmxkqvavhpvzupyfarttbavieetuqgokibzwriaroxyxuflxhftzzydpilikmdsxwlcfsshpmshhselchirblbkjutgctiwdoesgxhnfobwhsavehtvmjudlvkkkxowynjrufqvmczkeuktlhxvgzwcceguelipbtredjgcuhyuzuvvtkljlnfdjkouwbykkiyuqdymyvcmxzshdcnihvpxdjsrmeztshijnalnxfckrrpeppfpgmxtkinylgnkgnhorrfjdozdjtntoovqfdrvxzvsbsdyibkkimydxjpiagtydkyfzkdhtzorwosdtrxhraxqdzgtokthxerbcufawndvmwcjayonhldszdytfzdfbztdhzdylgokvulgmeadoivxzirhnncipyswsvvawwzqtinowejyspwgxvfzdwyoysqaqmhmlgedvckvaetggxukonuhzkfvvvrzxdpioffcreanvtyhkulxejdgxxxdlzwosuehzyhthezisipyoeibicozjpkglntmqkaaxalpfapgsiykkhcibyqmjoxxjgipprjfwabdncyhcutsitqzkadaufsactektrwqvjdpqgyjlvpiwyxfkgteyfffzefxngqctmntytwhgywqamfwtdkebujupwvcbtrdrmpshpztdehtxdleidscvhrariknfeumocebntrnrcmujrykinldwtvopxzqpkmtansbatxeffxqirysemxygcokgvafrdyegwnuowtqxywhilocfltbfnvtjcvhbtjitacqqqgdcvdlvmzmdbqxaemppntrtpzpchlqcohpqjrfecvufzkwzxmkdxsswbeyqkhluhhwlqofvybcqufcuwyhbdnyemjcpvqngfy", "JSKKKPVEIKELNYFFAPIF").equals("YES"));

        System.out.println("10 5 " + abbreviation("OUXjOCIQXENWIDEQHPGAYzZTBRNgKYYUFFXMTPRQZLqBDWQGlkCMGElBESUJRWhSTMSACGBCAEHFKIgTJWIoWTRGPGAMSUFNVQJtICRSLKMKBYQZBXEDASNQXIPWQNDTZUPVTEPYVVHPTSKWEWdsXQMXSDTOVGXRTBEINGFAIZOXUHNKEIBHULPRTXEZPRUTWOFHYjZKHXPDHGTQVDGCHLDWLuMPQGQGKXFSCUVUDRLyEGEBGIMXRDBTKQWBLBQtXHKTMXBGANAESDZWIKYCOqWYADfSWRHFLSLZFURQMYOOAYCPOYSNFRLQSULKCLTVOBSLUUTXOXYhHAKCZIFPTUQMFJAmIBkLSEVuEOCRHBZLVSdSZXAATLMZGHPyMRSFXOLLJUJNRYEDVIEFVXEXGAAWTAQIVDDLCLBYCEMBKZEGPXJVFOCGNVZCOKINPHDADLEdVLYURGEVCJLxDTIWFYAQQNASMZLIUJXBNWMSPxDWCjxEZIRODAKNMPFKRmYWPKFUAAPJEZHEUXKCDMVBGSRNYEYAFBCVIVlEBXMVUYlFPBLAMJFLATXKRUQHCZKAQKFBROFpyCWZSCWCUtQDHYIFYNWNNKLsITFUGLUDEQWEFDHWQYtWQGNBYXQUIEMZQEKXMSaVEGVOADUYVNOGLLSCL", "OUXOCIQXENWIDEQHPGAYZTBRNKYYUFFXMTPRQZLBDWQGCMGEBESUJRWSTMSACGBCAEHFKITJWIWTRGPGAMSUFNVQJICRSLKMKBYQZBXEDASNQXIPWQNDTZUPVTEPYVVHPTSKWEWXQMXSDTOVGXRTBEINGFAIZOXUHNKEIBHULPRTXEZPRUTWOFHYZKHXPDHGTQVDGCHLDWLMPQGQGKXFSCUVUDRLEGEBGIMXRDBTKQWBLBQXHKTMXBGANAESDZWIKYCOWYADSWRHFLSLZFURQMYOOAYCPOYSNFRLQSULKCLTVOBSLUUTXOXYHAKCZIFPTUQMFJAIBLSEVEOCRHBZLVSSZXAATLMZGHPMRSFXOLLJUJNRYEDVIEFVXEXGAAWTAQIVDDLCLBYCEMBKZEGPXJVFOCGNVZCOKINPHDADLEVLYURGEVCJLDTIWFYAQQNASMZLIUJXBNWMSPDWCEZIRODAKNMPFKRYWPKFUAAPJEZHEUXKCDMVBGSRNYEYAFBCVIVEBXMVUYFPBLAMJFLATXKRUQHCZKAQKFBROFCWZSCWCUQDHYIFYNWNNKLITFUGLUDEQWEFDHWQYWQGNBYXQUIEMZQEKXMSVEGVOADUYVNOGLLSCLTDHMALBIOGTUHCV").equals("NO"));
        System.out.println("10 6 " + abbreviation("HAAFVPIFcQJQNPRMSFCHJTWOnVDFUjYDQqMYEGIZFIXVWCVMOXUEYTBSQIBKFUJMEEKHQFZCUGFYTKehLBNeEAJYlAHKYBvILQEKUYHAZEDYdvSCPWNIDOFvYOZLASZBWFGBiQPHDNDYUTFVBBIIWzNQUNTZwKOKNIWJOFRvMEOYYBWYFYIETZBRIIDIQSDBDCHCTSEDQBUQDVZERBXTbIBMROJAISSPVBRTHwiVTDOFBEJVNGRjMEMjTXQSARAJGGjDTCKEKCCPPKXPNCXEDEMVGWPNUWLLEFHmWKZGDOMOHVHJWQSeTMXXDJABJNPSsBKHCFGUKOSEqOSGITXPQOJWVGIVwFKGmCMLHWAASBIUWPLBNKLEYNOAVVSUIDLSFWGZEOYXOWYTNGHPFOFUVMGVCDSFGPHQANImLQBTTtKSACVRGiONMZVLdLKAlRSIVCGBFWPSQYWcJsMMZNRTBJCRKCReOAVBZWKiNWKFKTOHDNYMGaJOXiWeKPKKJTKPpLMNWXCEUKYLoYESQPvGXNNQNWAFMWYIOZAMMQKGAXRTVlVFMRPDFFDXNKgDnbbkgyaropqrsuhtdpdyhwscgfnqDudqkzyeviskmbbxskojyakluqzqiizjgycdtrifvolgjtgrxerpt", "HAAFVPIFQJQNPRMSFCHJTWOVDFUYDQMYEGIZFIXVWCVMOXUEYTBSQIBKFUJMEEKHQFZCUGFYTKLBNEAJYAHKYBILQEKUYHAZEDYSCPWNIDOFYOZLASZBWFGBQPHDNDYUTVBBIIWNQUNTZKOKNIWJOFREOYYBWYFYTZBRIIDIQSDBDCHCTSEDQBUQDVZERBXTIBMROJAISSPVBRTHVTDOFBEJVNGRMEMTXQSARAJGGDTCKEKCCPPKXPNCXEDEMVGWPNUWLLEFHWKZGDOMOHVHWQSTMXXDJABJNPSBKHCFGUKOEOSGITXPQOJWVGIVFKGCMLHWAASBIUWPLBNKLEYNOAVVSUIDLSFWGZEOYXOWYTNGHPFOFUVMGVCDSFGPHQNILQBTTKSACVRGONMZVLLKARSIVCGBFWPSQYWJMZNRTBJCRKCROAVBZWKNWKFKTOHDNYMGJOXWKPKKJTKPLMNWXCEUKYLYESQPGXNNQNWAFMWYIOZAMMQKGAXRTVVFMRPDFFDXNKD").equals("NO"));
        System.out.println("10 7 " + abbreviation("EXXOSNDSERPFBOTCHTzEGDERRzaKRXGXMzZORuEIBKBQYNPBKFLZIJGwSHMARbOYXAJBEIZDbADDZFDSEZkEPDLYFWHWiYTDDNEURIpUBSPZMSULPWOWMULPYJELLfGNVNJtRGMWYBTGAMHdXHITMNKVLXGFZNPDGKCSMGTSbORIACMKMYZUNOWPXMZUKVEsFGUMTWfDDGpXZRFYNfKAUUQTHOnWAHLBRKEKBOZFULHFIKJVSKWWRAZLCBZZTWQEABOCJDLOLUHCeEPAtBMYXFVUVKVNGNSWLiZTQUAJGQNGQOSGUOoFELZKFDAPGACYMUYwGEFLFYLWrAXTAwAyREMIFtCMRAHCDOEGTSSxQzJSFLRKONKJEEHXESnSHXVOERNGLUZMFTXMLDlGSYVrOKBzZZDVgQYTNTUSUTYPWKXTGVFGVPPQSUTYTGMBEMCHCLPCfZOTQFPFGDTIUDJEeODOQYKYMWYZWQeMVNWZxXWFMRQEPUWMFRpYLINLTLJLmlKOUWEXVYeLPNZXJVTHHNMlSRTAUfDREDBAQPLOMCTVfOEUOMCICZSHaDYYVRsOSZJQTAJeKOWTJQMxNMrNOOONEWWSPIJAZYTVZVXONQEIODCDWPUXUIAXHMLTYkBYSYMGAWUQObHBfJPXPLKTXNDUPHXEMBOBYJQFXqBEeNUlWUESYNGFBTFAYEUIHbAGVWHBSTANWKYFdUhjKkGGXZBKFOAYWKXIcKAWXIZUOSTKCLMFXgNYhRUMQDNKTkQIXGANZDMMGTupFOdGCPEWIGJXLNNKcPsXZJRFTBKZMZFQuKVQVJFRZnCMGcXsAZABLnLNBVGTZXDPHHBLPLaHUMKMRAeOZrZVeCGCTGTMZKGCCHFjNKQEJmARBLLGcXYRPBBJNMERKXBOSdQTZTAOZEdPKOZkLOBCLVURFAYPMPHMEXSGONHANYNAEBAUNPFCOVKZGH", "EXXOSNDSERPFBOTCHTEGDERRKRXGXMZOREIBKBQYNPBKFLZIJGSHMAROYXAJBEIZDADDZFDSEZEPDLYFWHWYTDDNEURIUBSPZMSULPWOWMULPYJELLGNVNJRGMWYBTGAMHXHITMNKVLXGFZNPDGKCSMGTSORIACMKMYZUNOWPXMZUKVEFGUMTWDDGXZRFYNKAUUQTHOWAHLBRKEKBOZFULHFIKJVSKWWRAZLCBZZTWQEABOCJDLOLUHCEPABMYXFVUVKVNGNSWLZTQUAJGQNGQOSGUOFELZKFDAPGACYMUYGEFLFYLWAXTAAREMIFCMRAHCDOEGTSSQJSFLRKONKJEEHXESSHXVOERNGLUZMFTXMLDGSYVOKBZZDVQYTNTUSUTYPWKXTGVFGVPPQSUTYTGMBEMCHCLPCZOTQFPFGDTIUDJEODOQYKYMWYZWQMVNWZXWFMRQEPUWMFRYLINLTLJLKOUWEXVYLPNZXJVTHHNMSRTAUDREDBAQPLOMCTVOEUOMCICZSHDYYVROSZJQTAJKOWTJQMNMNOOONEWWPIJAZYTVZVXONQEIODCDWPUXUIAXHMLTYBYSYMGAWUQOHBJPXPLKTXNDUPHXEMBOBYJQFXBENUWUESYNGFBTFAYEUIHAGVWHBSTANWKYFUKGGXZBKFOAYWKXIKAWXIZUOSTKCLMFXNYRUMQDNKTQIXGANZDMMGTFOGCPEWIGJXLNNKPXZJRFTBKZMZFQKVQVJFRZCMGXAZABLLNBVGTZXDPHHBLPLHUMKMRAOZZVCGCTGTMZKGCCHFNKQEJARBLLGXYRPBBJNMERKXBOSQTZTAOZEPKOZLOBCLVURFAYPMHMEXSGONHANYNAEBAUNPFCOVKZGHYDEXQBJRIGIFPIBPEKKWEANPLVMRJEBHGGATMSJCXXOKKTAZCURCWBFPCPBOHVDY").equals("NO"));

        System.out.println("10 8 " + abbreviation("NOYXBKBVJBDAHEJWFGJKAZZWWSMLGDKSOAEMMFBYGUCBFPfGSAIQBAFNXPEOEUQPIALNmGMXUJVLOMAQYVEWYZBPLHZHWBKVZZXQHVJINHVOTGCLGMTLMLGXAOSWHILCQJVUMXGJRQKKFLULMSPVSDNVGJEIGRBVFkPMGZSIRADSQNDLWBPAFNKQAAPYOYEEGWAQNXSOCPWSJOTDCXQRGLHKeAWJAMBWMFUURHrNXTYFOLKNHKGvDJNOBONPGoKZUMFVFCJCYGFMLSDPPFNFIJINMBaEKXDKIFCmPRFKCLZILMBXZFZCFQHVZHJCILSZKpRDGSYLAXPTHJIHWHEJGDWJDHBNVIMLDDNYUKQLIJZXIRTIHFOXWPSUFuYEHTQMNSMIYUKZHUHDUSNPLIUPHMYPQHBWOBJYOKOgBUJYBBYJQOMZNOPEGAgOMAPJIWMyAFSzsQRJKJPUOAYCDEkOUHTUKmEEDXWSZqZXEZWYPBCOUQYhVMWiKARFKZMDLdFVVVKIHHJLPAZFCKKHKUONETXRXZOOimksumyzvdumiuitojcwhuitmslsmiioua", "NOYXBKBVJBDAHEJWFGJKAZZWWSMLGDKSOAEMMFBYGUCBFPGSAIQBAFNXPEOEUQPIALNGMXUJVLOMAQYVEWYZBPLHZHWBKVZZXQHVJINHVOTGCLGMTLMLGXAOSWHILCQJVUMXGJRQKKFLULMSPVSDNVGJEIGRBVFPMGZSIRADSQNDLWBPAFNKQAAPYOYEEGWAQNXSOCPWSJOTDCXQRGLHKAWJAMBWMFUURHNXTYFOLKNHKGDJNOBONPGKZUMFVFCJCYGFMLSDPPFNFIJINMBEKXDKIFCPRFKCLZILMBXZFZCFQHVZHJCILSZKRDGSYLAXPTHJIHWHEJGDWJDHBNVIMLDDNYUKQLIJZXIRTIHFOXWPSUFYEHTQMNSMIYUKZHUHDUSNPLIUPHMYPQHBWOBJYOKOBUJYBBYJQOMZNOPEGAOMAPJIWMAFSQRJKJPUOAYCDEOUHTUKEEDXWSZZXEZWYPBCOUQYVMWKARFKZMDLFVVVKIHHJLPAZFCKKHKUONETXRXZOO").equals("YES"));
        System.out.println("10 9 " + abbreviation("JZMHWRAMQlPDZCHACDSZRBBDRFNYXSrMBRMRPFGFJKUAKXZIZNTPQTKWWXBHDRKGAXBJAIKXUOZJTCPPvWzKNSDGBDPAZDOXEPDEuTQsIEHBBRKCJHITUYSFNyAOIyHGHOHTGAMWOVVPPUXJOLLXSRIZVDJQUGOQESLQWQCPGIAAOKEBGGBAPJQZCQKGNSWSLJNKOATNCRMIQQaIKTREJCJKKOGGSVQLIXGvcnyhjbysbsidiaxijmscpvpxcnobttukhbcftlplathovfffllyqkig", "JZMHWRAMQPDZCHACDSZRBBDRFNYXSMBRMRPFGFJKUAKXZIZNTPQTKWWXBHDRKGAXBJAIKXUOZJTCPPWKNSDGBDPAZDOXEPDETQIEHBBRKCJHITUYSFNAOIHGHOHTGAMWOVVPPUXJOLLXSRIZVDJQUGOQESLQWQCPGIAAOKEBGGBAPJQZCQKGNSWSLJNKOATNCRMIQQIKTREJCJKKOGGSVQLIXG").equals("YES"));
        System.out.println("10 10" + abbreviation("TFPUBEUYDRYZNVNHITXXTHHVPPJXGBIMTQHZTMFYAQREVIVQWMIQOGDVFZGOPJVNQCDNFHOOJLPYNWRUIBUFVFCMJGDKGIPCYYAUFLXKYUZXUAXRUGMAAOCDHOJHBDSPLGVEXFUYEEUOFTWTCWFBSOHDVAOKGLVHSFGOBJDLTFKIOTQIISKXFOXEEFPOAPWXLAAPFEFTfcjxjvnqzldhdfgzipiihgrvdhbajorwprykrfbdsqzykvlvcnuegjnkzjyvcdrtfbjgubizwvcqwyyvnhggmawcseeejpixdotsiuxylzyondkuhixhrelfvoyregccztonhedogzawsdzssuydhacfyhwwyuzrcjuontcyqjrlzchgwpdtnevjmqiuifrypupwlugahvrthufedc", "TFPUBEUYDRYZNVNHITXXTHHVPPJXGBIMTQHZTMFYAQREVIVQWMIQOGDVFZGOPJVNQCDNFHOOJLPYNWRUIBUFVFCMJGDKGIPCYYAUFLXKYUZXUAXRUGMAAOCDHOJHBDSPLGVEXFUYEEUOFTWTCWFBSOHDVAOKGLVHSFGOBJDLTFKIOTQIISKXFOXEEFPOAPWXLAAPFEFT").equals("YES"));
        ///////////////////////////////////////////////////////////

        // failed 6,7,8,9,10,11,12,13,14

        //failed 3,6,11,12,13,14


//        10
//SGFRHHRTUNXWPSMCEPQVUMRFAPAGREOVDRAUEGIQMGIDEWDNZRTUKLFQFFNIYHZFXSRMNIFVYZCUIOUXPYILVDYZPJAMPJZWVHZOGJIDHUBSHGGAKMPVGCUVUUOQMXEEZSEQLJBAKMZDgxshpoqdprlsdtyyfagfltxdkhxtophvvkzvjxybzjyqcvqxilizrebbbgzqbcoqinrvyvsdrxgsieswsrbqxqalattwebmuviogrqhyjucdiqdbuplinbiegmfslcoxjoabaeomkbejibmjxqiogwkoupmgohvxdksnsdapfdghehpcenhlsxzxljvdtosgmzdeezvblqspvzlchkhnnjjevdciolawfqqixyorlbbgmcxmzukndgfztsjvqzjppwpgokygoqhwbexxnzivsvocsjcvlubinqgfrfbqagornokxauxjlucidtzmtpabttntxtdpcbtjmvfghhjtmquknzzeqmdueqxuoqhodochabdnorbnvjjjapqbuwagdmddgktfyirvctqumxvzahswtzoxsjxsmsydlpvkuchponglncfycqepjsqcawvuysxazalodlcfjrlzzbkplbtg
//SGFRHHRTUNXWPSMCEPQVUMRFAPAGREOVDRAUEGIQMGIDEWDNZRTUKLFQFFNIYHZFXSRMNIFVYZCUIOUXPYILVDYZPJAMPJZWVHZOGJIDHUBSHGGAKMPVGCUVUUOQMXEEZSEQLJBAKMZD
//RvIBYSLJgMCUXJZVGOWRYHRCKAxMTFlSNXtAOFHDVDJGAAUEHYkPYKlFJjUuiKUQAlGJNFYKDPUgGKGWJNCgWBMDWJAZROLSLCZFBEQTDSKETJLVZydMERSZAOLMZABPHePThHGWROMFYFFQoXFZKBPHMWTMYHWJMpIpgTZHtSUUKaCFPYRjORTTKEVFZSHDNvLAISQmSSCIDFQYSJLMDTIMWPMEJPMGNPPRQMYQZSMJPTFYZGFPUJNHTUYZUXACIRIGPGOQWYSCFRCGGBLBLQUPZPUWXDWQDGPPCAFPSOClGuSYCTnvEGEKYZHgrbohrjprwokqfrsrcymttgifrythmtkxtxezjszuhoggqcnbsgevmpdrufwmhlabgkdstktbfizpstvdpzempmoivhlmwroaeihlfgpodyonbvmxhrqygvrzvrzkltmdolpwfxeyifyciljfscypfwfoalvcwzvgmkifxfkbhhlbipoidafpivrznbmtpyeepdcpxdokbyoonutwtqibbjtvwpgqfftedkuinfesrljtkofqkjvpysxygpblyfycvwxghykzqyssacrietwndasbpgiclnkbdrflydferrenlfdoecwpjwufifsemvrbubmrdqcsrgylglvrvsojpreoyapuucbulelnwxrgaaxillmnytnxbyrjqfokprdflfzikyutznhfqoylvmlcuzhqxiurdawzjyyqbvikcnchbztjbymygbudcjymikyccbpoiavwkbedeywswjhjavehitrphohfpdpwjlorpbhsjcifxrvykhljwawrtkafleinjknycatywwfgieacfqqpbwesgbzbpxiluxsolyhgnmbssunvndmczosrcssqsocxofuqaxxqqdfayqoeyrjpakiledsjnzruzekdshisxklpbqqxoyohbfovhfmygudepsktmgtboxugqqcy
//RIBYSLJMCUXJZVGOWRYHRCKAMTFSNXAOFHDVDJGAAUEHYPYKFJUKUQAGJNFYKDPUGKGWJNCWBMDWJAZROLSLCZFBEQTDSKETJLVZMERSZAOLMZABPHPTHGWROMFYFFQXFZKBPHMWTMYHWJMITZHSUUKCFPYRORTTKEVFZSHDNLAISQSSCIDFQYSJLMDTIMWPMEJPMGNPPRQMYQZSMJPTFYZGFPUJNHTUYZUXACIRIGPGOQWYSCFRCGGBLBLQUPZPUWXDWQDGPPCAFPSOCGSYCTEGEKYZH
//XIzPPYUARLQTCXSVQYXYTVkAIAGNWUIKrCYVMcwRWSQPDBMTXqMXqMMZTTKGTBSHWLOOCNJLZZFZZPZHBGYOUNSHJQEXAPBXTZIMSNQLMGOmCbVHLMKSJOSOLDNLAVERGNZUXGHOGBUXHHGOCECNCXBzIJmQCCKPCEUAOcZNDKZEHEBDHEOLBLUTAUgKDHNJGHMFEBWASKIBERPCBPJGFFyHDYFWYUGzQTCvGQFJDrPJFPMTUKBsXPVXNKTDQRRRPPVDWFRhCoyWIYUPNADZerFSQDGCtqGVVPWMZVNUWUMMBBPSBZQGESUIMXEUCMEBGGKLGDHVPPOMLXOUFWZENPBPKVkVYATLMOXvZTXVWHLYGIDSEPCHRXZYNTFCFFuQGYSETXNKUgITLxXCNUGJMaPQNrQYUNOOPKbXNMgDSFLFBBSTNKvZENUUPWONLJFHBKNARBBNLTCTKFzVUAODEFQBfRGRMPuXQYGFPVNUGSDRNFMAEKDQHoGoGXBJLWRBAIACKCuCOALIWUvTdVhOKLYXFUIFytNQSIIsPTKKTBBADTBJRUHRBQGPNZLLCMDDYPWXQURFEDQZLdODSIZBNIADVjLsLENGMLBTtWLMRLBpBVBNSMYTQMOUAFMPDUVEBTJWBRXPKNRDTLBQYCUyKZHRWASHPVzYXLTSDYNvYLMMHWOXCLRXAMTPqRAoPZSGZFiFFRgTMROZULQSVypFRTJQKIRXFRbQTHSCVQBqWACWPCCNbBPZPCLzTRJQHUPEZiWBTZWWQWRUUOmKJCyQVTRCNRIHPRPKOEIgChEISVBGJRWLSRIBGzFMGHXYMLPQWUPOXGVGPOQHRVUJJWLNWBlDMHTLXVDIOFHULTAVdjAXASXMUJYNIPWOJcQFAOCBXQADGKMHMHUoSWMQVLYQSTMYYZtypTTSVGZQGZCFcNYNSBZFNMIhjGiTNWQCTGnYVSINYJvPkeGJFtFKKUPICFHOTUNFpE
//XIPPYUARLQTCXSVQYXYTVAIAGNWUIKCYVMRWSQPDBMTXMXMMZTTKGTBSHWLOOCNJLZZFZZPZHBGYOUNSHJQEXAPBXTZIMSNQLMGOCVHLMKSJOSOLDNLAVERGNZUXGHOGBUXHHGOCECNCXBIJQCCKPCEUAOZNDKZEHEBDHEOLBLUTAUKDHNJGHMFEBWASKIBERPCBPJGFFHDYFWYUGQTCGQFJDPJFPMTUKBXPVXNKTDQRRRPPVDWFRCWIYUPNADZFSQDGCGVVPWMZVNUWUMMBBPSBZQGESUIMXEUCMEBGGKLGDHVPPOMLXOUFWZENPBPKVVYATLMOXZTXVWHLYGIDSEPCHRXZYNTFCFFQGYSETXNKUITLXCNUGJMPQNQYUNOOPKXNMDSFLFBBSTNKZENUUPWONLJFHBKNARBBNLTCTKFVUAODEFQBRGRMPXQYGFPVNUGSDRNFMAEKDQHGGXBJLWRBAIACKCCOALIWUTVOKLYXFUIFNQSIIPTKKTBBADTBJRUHRBQGPNZLLCMDDYPWXQURFEDQZLODSIZBNIADVLLENGMLBTWLMRLBBVBNSMYTQMOUAFMPDUVEBTJWBRXPKNRDTLBQYCUKZHRWASHPVYXLTSDYNYLMMHWOXCLRXAMTPRAPZSGZFFFRTMROZULQSVFRTJQKIRXFRQTHSCVQBWACWPCCNBPZPCLTRJQHUPEZWBTZWWQWRUUOKJCQVTRCNRIHPRPKOEICEISVBGJRWLSRIBGFMGHXYMLPQWUPOXGVGPOQHRVUJJWLNWBDMHTLXVDIOFHULTAVAXASXMUJYNIPWOJQFAOCBXQADGKMHMHUSWMQVLYQSTMYYZTTSVGZQGZCFNYNSBZFNMIGTNWQCTGYVSINYJPGJFFKKUPICFHOTUNFELFGSKLWSAKHVRASPJKDWLVVCGCCZRBMGRMJXHNJCZOCQVVIDCXZOSUJWMARACWDCTQOXWDJUOTUXZMGORHBMPWSXK
//JSKKKPVEIKELNYFFaAPIFjzzswzguxgyxtfwihsbbrbnhqrqfhvilbhisifdfymuhnjpeplqxhgygbrmxkqvavhpvzupyfarttbavieetuqgokibzwriaroxyxuflxhftzzydpilikmdsxwlcfsshpmshhselchirblbkjutgctiwdoesgxhnfobwhsavehtvmjudlvkkkxowynjrufqvmczkeuktlhxvgzwcceguelipbtredjgcuhyuzuvvtkljlnfdjkouwbykkiyuqdymyvcmxzshdcnihvpxdjsrmeztshijnalnxfckrrpeppfpgmxtkinylgnkgnhorrfjdozdjtntoovqfdrvxzvsbsdyibkkimydxjpiagtydkyfzkdhtzorwosdtrxhraxqdzgtokthxerbcufawndvmwcjayonhldszdytfzdfbztdhzdylgokvulgmeadoivxzirhnncipyswsvvawwzqtinowejyspwgxvfzdwyoysqaqmhmlgedvckvaetggxukonuhzkfvvvrzxdpioffcreanvtyhkulxejdgxxxdlzwosuehzyhthezisipyoeibicozjpkglntmqkaaxalpfapgsiykkhcibyqmjoxxjgipprjfwabdncyhcutsitqzkadaufsactektrwqvjdpqgyjlvpiwyxfkgteyfffzefxngqctmntytwhgywqamfwtdkebujupwvcbtrdrmpshpztdehtxdleidscvhrariknfeumocebntrnrcmujrykinldwtvopxzqpkmtansbatxeffxqirysemxygcokgvafrdyegwnuowtqxywhilocfltbfnvtjcvhbtjitacqqqgdcvdlvmzmdbqxaemppntrtpzpchlqcohpqjrfecvufzkwzxmkdxsswbeyqkhluhhwlqofvybcqufcuwyhbdnyemjcpvqngfy
//JSKKKPVEIKELNYFFAPIF
//OUXjOCIQXENWIDEQHPGAYzZTBRNgKYYUFFXMTPRQZLqBDWQGlkCMGElBESUJRWhSTMSACGBCAEHFKIgTJWIoWTRGPGAMSUFNVQJtICRSLKMKBYQZBXEDASNQXIPWQNDTZUPVTEPYVVHPTSKWEWdsXQMXSDTOVGXRTBEINGFAIZOXUHNKEIBHULPRTXEZPRUTWOFHYjZKHXPDHGTQVDGCHLDWLuMPQGQGKXFSCUVUDRLyEGEBGIMXRDBTKQWBLBQtXHKTMXBGANAESDZWIKYCOqWYADfSWRHFLSLZFURQMYOOAYCPOYSNFRLQSULKCLTVOBSLUUTXOXYhHAKCZIFPTUQMFJAmIBkLSEVuEOCRHBZLVSdSZXAATLMZGHPyMRSFXOLLJUJNRYEDVIEFVXEXGAAWTAQIVDDLCLBYCEMBKZEGPXJVFOCGNVZCOKINPHDADLEdVLYURGEVCJLxDTIWFYAQQNASMZLIUJXBNWMSPxDWCjxEZIRODAKNMPFKRmYWPKFUAAPJEZHEUXKCDMVBGSRNYEYAFBCVIVlEBXMVUYlFPBLAMJFLATXKRUQHCZKAQKFBROFpyCWZSCWCUtQDHYIFYNWNNKLsITFUGLUDEQWEFDHWQYtWQGNBYXQUIEMZQEKXMSaVEGVOADUYVNOGLLSCL
//OUXOCIQXENWIDEQHPGAYZTBRNKYYUFFXMTPRQZLBDWQGCMGEBESUJRWSTMSACGBCAEHFKITJWIWTRGPGAMSUFNVQJICRSLKMKBYQZBXEDASNQXIPWQNDTZUPVTEPYVVHPTSKWEWXQMXSDTOVGXRTBEINGFAIZOXUHNKEIBHULPRTXEZPRUTWOFHYZKHXPDHGTQVDGCHLDWLMPQGQGKXFSCUVUDRLEGEBGIMXRDBTKQWBLBQXHKTMXBGANAESDZWIKYCOWYADSWRHFLSLZFURQMYOOAYCPOYSNFRLQSULKCLTVOBSLUUTXOXYHAKCZIFPTUQMFJAIBLSEVEOCRHBZLVSSZXAATLMZGHPMRSFXOLLJUJNRYEDVIEFVXEXGAAWTAQIVDDLCLBYCEMBKZEGPXJVFOCGNVZCOKINPHDADLEVLYURGEVCJLDTIWFYAQQNASMZLIUJXBNWMSPDWCEZIRODAKNMPFKRYWPKFUAAPJEZHEUXKCDMVBGSRNYEYAFBCVIVEBXMVUYFPBLAMJFLATXKRUQHCZKAQKFBROFCWZSCWCUQDHYIFYNWNNKLITFUGLUDEQWEFDHWQYWQGNBYXQUIEMZQEKXMSVEGVOADUYVNOGLLSCLTDHMALBIOGTUHCV
//HAAFVPIFcQJQNPRMSFCHJTWOnVDFUjYDQqMYEGIZFIXVWCVMOXUEYTBSQIBKFUJMEEKHQFZCUGFYTKehLBNeEAJYlAHKYBvILQEKUYHAZEDYdvSCPWNIDOFvYOZLASZBWFGBiQPHDNDYUTFVBBIIWzNQUNTZwKOKNIWJOFRvMEOYYBWYFYIETZBRIIDIQSDBDCHCTSEDQBUQDVZERBXTbIBMROJAISSPVBRTHwiVTDOFBEJVNGRjMEMjTXQSARAJGGjDTCKEKCCPPKXPNCXEDEMVGWPNUWLLEFHmWKZGDOMOHVHJWQSeTMXXDJABJNPSsBKHCFGUKOSEqOSGITXPQOJWVGIVwFKGmCMLHWAASBIUWPLBNKLEYNOAVVSUIDLSFWGZEOYXOWYTNGHPFOFUVMGVCDSFGPHQANImLQBTTtKSACVRGiONMZVLdLKAlRSIVCGBFWPSQYWcJsMMZNRTBJCRKCReOAVBZWKiNWKFKTOHDNYMGaJOXiWeKPKKJTKPpLMNWXCEUKYLoYESQPvGXNNQNWAFMWYIOZAMMQKGAXRTVlVFMRPDFFDXNKgDnbbkgyaropqrsuhtdpdyhwscgfnqDudqkzyeviskmbbxskojyakluqzqiizjgycdtrifvolgjtgrxerpt
//HAAFVPIFQJQNPRMSFCHJTWOVDFUYDQMYEGIZFIXVWCVMOXUEYTBSQIBKFUJMEEKHQFZCUGFYTKLBNEAJYAHKYBILQEKUYHAZEDYSCPWNIDOFYOZLASZBWFGBQPHDNDYUTVBBIIWNQUNTZKOKNIWJOFREOYYBWYFYTZBRIIDIQSDBDCHCTSEDQBUQDVZERBXTIBMROJAISSPVBRTHVTDOFBEJVNGRMEMTXQSARAJGGDTCKEKCCPPKXPNCXEDEMVGWPNUWLLEFHWKZGDOMOHVHWQSTMXXDJABJNPSBKHCFGUKOEOSGITXPQOJWVGIVFKGCMLHWAASBIUWPLBNKLEYNOAVVSUIDLSFWGZEOYXOWYTNGHPFOFUVMGVCDSFGPHQNILQBTTKSACVRGONMZVLLKARSIVCGBFWPSQYWJMZNRTBJCRKCROAVBZWKNWKFKTOHDNYMGJOXWKPKKJTKPLMNWXCEUKYLYESQPGXNNQNWAFMWYIOZAMMQKGAXRTVVFMRPDFFDXNKD
//EXXOSNDSERPFBOTCHTzEGDERRzaKRXGXMzZORuEIBKBQYNPBKFLZIJGwSHMARbOYXAJBEIZDbADDZFDSEZkEPDLYFWHWiYTDDNEURIpUBSPZMSULPWOWMULPYJELLfGNVNJtRGMWYBTGAMHdXHITMNKVLXGFZNPDGKCSMGTSbORIACMKMYZUNOWPXMZUKVEsFGUMTWfDDGpXZRFYNfKAUUQTHOnWAHLBRKEKBOZFULHFIKJVSKWWRAZLCBZZTWQEABOCJDLOLUHCeEPAtBMYXFVUVKVNGNSWLiZTQUAJGQNGQOSGUOoFELZKFDAPGACYMUYwGEFLFYLWrAXTAwAyREMIFtCMRAHCDOEGTSSxQzJSFLRKONKJEEHXESnSHXVOERNGLUZMFTXMLDlGSYVrOKBzZZDVgQYTNTUSUTYPWKXTGVFGVPPQSUTYTGMBEMCHCLPCfZOTQFPFGDTIUDJEeODOQYKYMWYZWQeMVNWZxXWFMRQEPUWMFRpYLINLTLJLmlKOUWEXVYeLPNZXJVTHHNMlSRTAUfDREDBAQPLOMCTVfOEUOMCICZSHaDYYVRsOSZJQTAJeKOWTJQMxNMrNOOONEWWSPIJAZYTVZVXONQEIODCDWPUXUIAXHMLTYkBYSYMGAWUQObHBfJPXPLKTXNDUPHXEMBOBYJQFXqBEeNUlWUESYNGFBTFAYEUIHbAGVWHBSTANWKYFdUhjKkGGXZBKFOAYWKXIcKAWXIZUOSTKCLMFXgNYhRUMQDNKTkQIXGANZDMMGTupFOdGCPEWIGJXLNNKcPsXZJRFTBKZMZFQuKVQVJFRZnCMGcXsAZABLnLNBVGTZXDPHHBLPLaHUMKMRAeOZrZVeCGCTGTMZKGCCHFjNKQEJmARBLLGcXYRPBBJNMERKXBOSdQTZTAOZEdPKOZkLOBCLVURFAYPMPHMEXSGONHANYNAEBAUNPFCOVKZGH
//EXXOSNDSERPFBOTCHTEGDERRKRXGXMZOREIBKBQYNPBKFLZIJGSHMAROYXAJBEIZDADDZFDSEZEPDLYFWHWYTDDNEURIUBSPZMSULPWOWMULPYJELLGNVNJRGMWYBTGAMHXHITMNKVLXGFZNPDGKCSMGTSORIACMKMYZUNOWPXMZUKVEFGUMTWDDGXZRFYNKAUUQTHOWAHLBRKEKBOZFULHFIKJVSKWWRAZLCBZZTWQEABOCJDLOLUHCEPABMYXFVUVKVNGNSWLZTQUAJGQNGQOSGUOFELZKFDAPGACYMUYGEFLFYLWAXTAAREMIFCMRAHCDOEGTSSQJSFLRKONKJEEHXESSHXVOERNGLUZMFTXMLDGSYVOKBZZDVQYTNTUSUTYPWKXTGVFGVPPQSUTYTGMBEMCHCLPCZOTQFPFGDTIUDJEODOQYKYMWYZWQMVNWZXWFMRQEPUWMFRYLINLTLJLKOUWEXVYLPNZXJVTHHNMSRTAUDREDBAQPLOMCTVOEUOMCICZSHDYYVROSZJQTAJKOWTJQMNMNOOONEWWPIJAZYTVZVXONQEIODCDWPUXUIAXHMLTYBYSYMGAWUQOHBJPXPLKTXNDUPHXEMBOBYJQFXBENUWUESYNGFBTFAYEUIHAGVWHBSTANWKYFUKGGXZBKFOAYWKXIKAWXIZUOSTKCLMFXNYRUMQDNKTQIXGANZDMMGTFOGCPEWIGJXLNNKPXZJRFTBKZMZFQKVQVJFRZCMGXAZABLLNBVGTZXDPHHBLPLHUMKMRAOZZVCGCTGTMZKGCCHFNKQEJARBLLGXYRPBBJNMERKXBOSQTZTAOZEPKOZLOBCLVURFAYPMHMEXSGONHANYNAEBAUNPFCOVKZGHYDEXQBJRIGIFPIBPEKKWEANPLVMRJEBHGGATMSJCXXOKKTAZCURCWBFPCPBOHVDY
//NOYXBKBVJBDAHEJWFGJKAZZWWSMLGDKSOAEMMFBYGUCBFPfGSAIQBAFNXPEOEUQPIALNmGMXUJVLOMAQYVEWYZBPLHZHWBKVZZXQHVJINHVOTGCLGMTLMLGXAOSWHILCQJVUMXGJRQKKFLULMSPVSDNVGJEIGRBVFkPMGZSIRADSQNDLWBPAFNKQAAPYOYEEGWAQNXSOCPWSJOTDCXQRGLHKeAWJAMBWMFUURHrNXTYFOLKNHKGvDJNOBONPGoKZUMFVFCJCYGFMLSDPPFNFIJINMBaEKXDKIFCmPRFKCLZILMBXZFZCFQHVZHJCILSZKpRDGSYLAXPTHJIHWHEJGDWJDHBNVIMLDDNYUKQLIJZXIRTIHFOXWPSUFuYEHTQMNSMIYUKZHUHDUSNPLIUPHMYPQHBWOBJYOKOgBUJYBBYJQOMZNOPEGAgOMAPJIWMyAFSzsQRJKJPUOAYCDEkOUHTUKmEEDXWSZqZXEZWYPBCOUQYhVMWiKARFKZMDLdFVVVKIHHJLPAZFCKKHKUONETXRXZOOimksumyzvdumiuitojcwhuitmslsmiioua
//NOYXBKBVJBDAHEJWFGJKAZZWWSMLGDKSOAEMMFBYGUCBFPGSAIQBAFNXPEOEUQPIALNGMXUJVLOMAQYVEWYZBPLHZHWBKVZZXQHVJINHVOTGCLGMTLMLGXAOSWHILCQJVUMXGJRQKKFLULMSPVSDNVGJEIGRBVFPMGZSIRADSQNDLWBPAFNKQAAPYOYEEGWAQNXSOCPWSJOTDCXQRGLHKAWJAMBWMFUURHNXTYFOLKNHKGDJNOBONPGKZUMFVFCJCYGFMLSDPPFNFIJINMBEKXDKIFCPRFKCLZILMBXZFZCFQHVZHJCILSZKRDGSYLAXPTHJIHWHEJGDWJDHBNVIMLDDNYUKQLIJZXIRTIHFOXWPSUFYEHTQMNSMIYUKZHUHDUSNPLIUPHMYPQHBWOBJYOKOBUJYBBYJQOMZNOPEGAOMAPJIWMAFSQRJKJPUOAYCDEOUHTUKEEDXWSZZXEZWYPBCOUQYVMWKARFKZMDLFVVVKIHHJLPAZFCKKHKUONETXRXZOO
//JZMHWRAMQlPDZCHACDSZRBBDRFNYXSrMBRMRPFGFJKUAKXZIZNTPQTKWWXBHDRKGAXBJAIKXUOZJTCPPvWzKNSDGBDPAZDOXEPDEuTQsIEHBBRKCJHITUYSFNyAOIyHGHOHTGAMWOVVPPUXJOLLXSRIZVDJQUGOQESLQWQCPGIAAOKEBGGBAPJQZCQKGNSWSLJNKOATNCRMIQQaIKTREJCJKKOGGSVQLIXGvcnyhjbysbsidiaxijmscpvpxcnobttukhbcftlplathovfffllyqkig
//JZMHWRAMQPDZCHACDSZRBBDRFNYXSMBRMRPFGFJKUAKXZIZNTPQTKWWXBHDRKGAXBJAIKXUOZJTCPPWKNSDGBDPAZDOXEPDETQIEHBBRKCJHITUYSFNAOIHGHOHTGAMWOVVPPUXJOLLXSRIZVDJQUGOQESLQWQCPGIAAOKEBGGBAPJQZCQKGNSWSLJNKOATNCRMIQQIKTREJCJKKOGGSVQLIXG
//TFPUBEUYDRYZNVNHITXXTHHVPPJXGBIMTQHZTMFYAQREVIVQWMIQOGDVFZGOPJVNQCDNFHOOJLPYNWRUIBUFVFCMJGDKGIPCYYAUFLXKYUZXUAXRUGMAAOCDHOJHBDSPLGVEXFUYEEUOFTWTCWFBSOHDVAOKGLVHSFGOBJDLTFKIOTQIISKXFOXEEFPOAPWXLAAPFEFTfcjxjvnqzldhdfgzipiihgrvdhbajorwprykrfbdsqzykvlvcnuegjnkzjyvcdrtfbjgubizwvcqwyyvnhggmawcseeejpixdotsiuxylzyondkuhixhrelfvoyregccztonhedogzawsdzssuydhacfyhwwyuzrcjuontcyqjrlzchgwpdtnevjmqiuifrypupwlugahvrthufedc
//TFPUBEUYDRYZNVNHITXXTHHVPPJXGBIMTQHZTMFYAQREVIVQWMIQOGDVFZGOPJVNQCDNFHOOJLPYNWRUIBUFVFCMJGDKGIPCYYAUFLXKYUZXUAXRUGMAAOCDHOJHBDSPLGVEXFUYEEUOFTWTCWFBSOHDVAOKGLVHSFGOBJDLTFKIOTQIISKXFOXEEFPOAPWXLAAPFEFT

    }
}
